/**
 * KalaSetu AI — Central Reactive State Manager
 * Built for low-spec laptops & mobile devices: Zero dependencies, zero memory leaks.
 */

class AppState {
  constructor() {
    this.state = {
      language: (typeof localStorage !== 'undefined' ? localStorage.getItem('kalasetu_lang') : null) || 'bn', // Default or persisted
      online: typeof navigator !== 'undefined' ? navigator.onLine : true,
      artisan: (typeof localStorage !== 'undefined' && JSON.parse(localStorage.getItem('kalasetu_artisan') || 'null')) || {
        name: 'Ramji Lal Meena',
        cluster: 'Bagru / Sanganer (Jaipur)',
        craft: 'Hand-block Textile & Natural Dye',
        phone: '+91 98765 43210'
      },
      activeTab: 'cataloger',
      pendingSyncCount: 0,
      userRole: (typeof localStorage !== 'undefined' ? localStorage.getItem('kalasetu_role') : null) || 'artisan',
      speechConfig: (typeof localStorage !== 'undefined' && JSON.parse(localStorage.getItem('kalasetu_speech_config') || 'null')) || {
        useCustomApi: false,
        apiUrl: '',
        apiKey: ''
      }
    };

    this.listeners = {};

    // Multi-language dictionary specifically designed for rural kaarigars across 9 Indian Languages
    this.translations = {
      en: {
        appName: "KalaSetu AI",
        tagline: "Virtual Business Manager for Artisans",
        listenTooltip: "Listen to explanation",
        onlineStatus: "Online · Ready to Sync",
        offlineStatus: "Offline Mode · Saved Locally",
        tabCataloger: "Voice Catalog",
        tabPricing: "Fair Price",
        tabHisab: "Hisab-Kitab",
        tabMarket: "Showcase & Decor",
        tabSettings: "Profile & Settings",
        tabFacilitator: "Facilitator Desk",
        capturePhoto: "Capture Craft Photo",
        cameraGuide: "Natural dye colors & round shapes preserved safely",
        holdToSpeak: "Hold & Speak About Craft",
        releaseToStop: "Release to generate digital listing",
        generateDraft: "AI Processing Voice Note...",
        listeningText: "Listening... speak in your language",
        speechPlaceholder: 'Say e.g.: "Bagru block print dupatta, 2.5m, natural indigo dye, took 2 days"',
        craftName: "Craft Name",
        craftType: "Craft Category",
        materials: "Materials Used",
        dimensions: "Dimensions / Size",
        makingTime: "Lead Time (Making Days)",
        careGuide: "Care Instructions",
        hindiDesc: "Hindi Description",
        englishDesc: "English Description",
        baseCostLabel: "Total Making Cost",
        suggestedRange: "Suggested Fair Price Range",
        confirmListingBtn: "Approve & Add to Catalog",
        shareWhatsappBtn: "Share on WhatsApp",
        artisanDecisionNote: "AI suggests, but YOU make the final decision.",
        dailyHisabTitle: "Daily Business Hisab-Kitab",
        hisabPrompt: 'Say: "Spent 500 on dyes and sold 2 dupattas for 3000 today"',
        recordExpenseIncome: "Voice Record Today's Numbers",
        incomeLabel: "Today's Sales",
        expenseLabel: "Today's Expenses",
        netProfitLabel: "Net Profit",
        spaceStagerTitle: "AI Room Decor & Stager",
        spaceStagerDesc: "Upload a room wall to see authentic crafts placed live",
        reelsSearchTitle: "Reels-to-Artisan Search",
        reelsSearchDesc: "Upload Instagram/social screenshot to match authentic craft",
        certifiedOrigin: "Authentic GI Cluster Verified",
        listenInstructions: "Listen to Instructions",
        colorPreservation: "Color Preservation",
        cameraCenterTip: "Keep craft centered inside box",
        tapToCapture: "Tap to take photo or upload",
        studioLighting: "Studio Lighting",
        cleanBackdrop: "Clean Backdrop",
        retake: "Retake",
        step2Title: "Speak About Your Craft",
        voicePromptHelp: "Mention craft name, materials, size, and making days:",
        sampleVoiceDemo: "⚡ Fill with Sample Voice Note (Live Demo)",
        step3Title: "AI Generated Digital Listing",
        reviewDraft: "Review Draft",
        authenticityConfirmation: "Authenticity Confirmation:",
        genuineHandcrafted: "100% Genuine Handcrafted",
        belongsToGiCluster: "Belongs to Registered GI Cluster",
        calculatePriceBtn: "Calculate Fair Price (Cost-Plus) →",
        approveListingBtn: "Approve & Add to Catalog ✓",
        listenPricingBreakdown: "Listen to Price Breakdown",
        explainablePricingTitle: "Explainable Cost-Plus Pricing Calculator",
        pricingFormulaSubtitle: "Every rupee explained clearly to eliminate buyer haggling.",
        rawMaterialCost: "Material & Natural Dye Cost",
        artisanLaborHours: "Artisan Labor (Hours)",
        hourlyWageBenchmark: "Hourly Wage Benchmark (₹80/hr)",
        giHeritagePremium: "GI Heritage Lineage Royalty (+15%)",
        pricingSummaryTitle: "Explainable Pricing Breakdown",
        totalDirectCost: "Total Production Cost",
        recommendedRetail: "Recommended Fair Retail Price",
        livingWageGuaranteed: "✓ Ensures ₹80/hr living wage benchmark + 15% heritage preservation royalty.",
        artisanProfileTitle: "Artisan Profile & Cluster Lineage",
        artisanNameLabel: "Artisan Name",
        craftLineageLabel: "Heritage Craft Specialization",
        recognizedClusterLabel: "Recognized Craft Cluster",
        phoneNumberLabel: "Phone Number (For SMS Alerts)",
        updateProfileBtn: "Update Profile",
        selectLanguageTitle: "Select Regional Language",
        chooseLangSubtitle: "Choose your preferred language for voice instructions & UI:",
        customAiTitle: "Custom Indian Language AI Model API",
        customAiSubtitle: "Plug in your external Indian Language STT/TTS model credits here (covers 6–9 regional languages):",
        saveAiCredentialsBtn: "Save AI Credentials",
        transparentCostPlus: "Transparent Cost-Plus",
        formulaCost: "Cost",
        formulaMaterial: "Material",
        formulaLabor: "Labor",
        formulaPackaging: "Packaging",
        formulaTransport: "Transport",
        formulaMargin: "Margin",
        formulaExplanation: "AI calculates a fair benchmark, but the final selling price is always your decision.",
        adjustCostBreakdown: "Adjust Your Cost Breakdown:",
        artisanLaborValue: "Artisan Labor Value",
        ecoPackaging: "Eco Packaging",
        localFreight: "Local Freight & Transport",
        desiredMargin: "Desired Profit Margin (%)",
        totalBaseCost: "Total Production Base Cost:",
        fairMarketRange: "Fair Market Range:",
        yourFinalPrice: "Your Final Chosen Price (₹):",
        lockPriceBtn: "Lock & Apply Price",
        priceLockedToast: "Price locked for listing!",
        listenHisabSummary: "Listen to Ledger Summary",
        dailyBusinessLedger: "Daily Business Ledger",
        addVoiceLedgerTitle: "Add Voice Ledger Entry",
        holdSpeakEntry: "Hold & Speak Entry",
        transcriptPlaceholder: "Your spoken words will appear here...",
        incomeSalesLabel: "Income / Sales (₹)",
        expenseCostLabel: "Expense / Purchases (₹)",
        entryDescLabel: "Entry Note / Craft Details",
        saveLedgerEntryBtn: "Save Entry to Daily Ledger",
        recentEntriesTitle: "Recent Voice & Manual Ledger Entries",
        noEntriesYet: "No entries recorded yet. Tap the microphone or add manually above.",
        ledgerEntrySavedToast: "Ledger entry saved!",
        artisanCatalogTab: "Artisan Catalog",
        aiSpaceStagerTab: "AI Space Stager",
        reelsToArtisanTab: "Reels-to-Artisan",
        digitalStorefrontTitle: "Your Digital Storefront",
        shareStoreBtn: "Share Store Link",
        shareCraftBtn: "Share",
        roomStagerTitle: "AI Room Decor & Space Stager",
        roomStagerSubtitle: "Place authentic handcrafted pottery and textiles directly into modern living rooms.",
        selectRoomPreset: "Select Room Setting:",
        roomModernLiving: "Modern Minimalist Living Room",
        roomCozyBedroom: "Artisan Heritage Bedroom",
        roomDiningWall: "Dining Accent Wall",
        renderStagedRoomBtn: "Stage Craft in Room (Neural Preview) 🎨",
        reelsMatcherTitle: "Reels-to-Artisan Visual Matcher",
        reelsMatcherSubtitle: "Reverse search viral Instagram/Pinterest reels directly to authentic craft clusters.",
        reelsDropzoneText: "Drop social media screenshot or tap to upload",
        reelsMatchingBtn: "Find Authentic Artisan Lineage 🔍",
        matchFoundTitle: "Verified Authentic Cluster Match:",
        enableCustomAiLabel: "Enable External Indian Language AI Model",
        apiEndpointLabel: "STT/TTS API Base Endpoint",
        apiKeyLabel: "Bearer API Key / Token",
        profileUpdatedToast: "Profile updated successfully!",
        aiConfigSavedToast: "AI Model API credentials saved!"
      },

      bn: {
        appName: "কলাসেতু AI",
        tagline: "কারিগরদের ডিজিটাল ব্যবসা সহায়ক",
        listenTooltip: "কণ্ঠস্বরে শুনুন",
        onlineStatus: "অনলাইন · সিঙ্ক করতে প্রস্তুত",
        offlineStatus: "অফলাইন মোড · লোকালভাবে সংরক্ষিত",
        tabCataloger: "কণ্ঠস্বর ক্যাটালগ",
        tabPricing: "ন্যায্য দাম",
        tabHisab: "হিসাব-কিতাব",
        tabMarket: "দোকান ও সাজসজ্জা",
        tabSettings: "প্রোফাইল ও সেটিংস",
        capturePhoto: "শিল্পের ছবি তুলুন",
        cameraGuide: "প্রাকৃতিক রঙ এবং খাঁটি রূপ সুরক্ষিত থাকবে",
        holdToSpeak: "চেপে ধরে পণ্যের বিবরণ বলুন",
        releaseToStop: "ছাড়লেই তালিকা তৈরি হবে",
        generateDraft: "AI আপনার কথা থেকে তালিকা তৈরি করছে...",
        listeningText: "শুনছি... আপনার ভাষায় বলুন",
        speechPlaceholder: 'যেমন বলুন: "শান্তিপুরী সুতির শাড়ি, প্রাকৃতিক নীল রঙ, ৩ দিন লেগেছে"',
        craftName: "পণ্যের নাম",
        craftType: "শিল্পের ধরণ",
        materials: "ব্যবহৃত উপকরণ",
        dimensions: "পরিমাপ / আকার",
        makingTime: "তৈরি করতে লাগা সময়",
        careGuide: "যত্নের পরামর্শ",
        hindiDesc: "আঞ্চলিক বিবরণ",
        englishDesc: "ইংরেজি বিবরণ (ক্রেতাদের জন্য)",
        baseCostLabel: "মোট উৎপাদন খরচ",
        suggestedRange: "AI প্রস্তাবিত ন্যায্য দাম",
        confirmListingBtn: "ক্যাটালগে যুক্ত করুন",
        shareWhatsappBtn: "হোয়াটসঅ্যাপে শেয়ার করুন",
        artisanDecisionNote: "AI শুধু পরামর্শ দেবে, চূড়ান্ত সিদ্ধান্ত আপনার।",
        dailyHisabTitle: "আজকের দৈনিক হিসাব-কিতাব",
        hisabPrompt: 'যেমন বলুন: "আজ ৫০০ টাকার রঙ কিনলাম ও দুটি শাড়ি ৩০০০ টাকায় বেচলাম"',
        recordExpenseIncome: "মুখে বলে আয়-ব্যয় নথিভুক্ত করুন",
        incomeLabel: "আজকের মোট বিক্রি",
        expenseLabel: "আজকের মোট খরচ",
        netProfitLabel: "আজকের লাভ",
        spaceStagerTitle: "ঘরের সাজসজ্জা (AI ডেকর)",
        spaceStagerDesc: "দেয়ালের ছবি দিয়ে দেখুন আপনার শিল্প কেমন সাজবে",
        reelsSearchTitle: "রিলস থেকে কারিগর সন্ধান",
        reelsSearchDesc: "সোশ্যাল মিডিয়া স্ক্রিনশট থেকে খাঁটি কারিগর মিলান",
        certifiedOrigin: "প্রত্যয়িত জিআই ক্লাস্টার কারিগর",
        listenInstructions: "নির্দেশনা শুনুন",
        colorPreservation: "রঙ সুরক্ষা চালু",
        cameraCenterTip: "সামগ্রীটি ফ্রেমের মাঝখানে রাখুন",
        tapToCapture: "ছবি তুলতে বা আপলোড করতে ট্যাপ করুন",
        studioLighting: "আলো উন্নত করুন",
        cleanBackdrop: "পটভূমি পরিষ্কার করুন",
        retake: "পুনরায় ছবি তুলুন",
        step2Title: "শিল্পকর্মের বিবরণ মুখে বলুন",
        voicePromptHelp: "নাম, কাপড়/উপকরণ, আকার এবং তৈরির সময় বলুন:",
        sampleVoiceDemo: "⚡ নমুনা কণ্ঠস্বর দিয়ে পরীক্ষা করুন (ডেমো)",
        step3Title: "AI প্রস্তুত ডিজিটাল ক্যাটালগ",
        reviewDraft: "যাচাই করুন",
        authenticityConfirmation: "সত্যতা প্রমাণীকরণ:",
        genuineHandcrafted: "১০০% খাঁটি হস্তনির্মিত পণ্য",
        belongsToGiCluster: "নিবন্ধিত জিআই ক্লাস্টার ভুক্ত",
        calculatePriceBtn: "ন্যায্য দাম হিসাব করুন (কস্ট-প্লাস) →",
        approveListingBtn: "অনুমোদন করুন ও যোগ করুন ✓",
        listenPricingBreakdown: "দামের হিসাব শুনুন",
        explainablePricingTitle: "স্বচ্ছ ন্যায্য মূল্য ক্যালকুলেটর",
        pricingFormulaSubtitle: "প্রতিটি টাকার স্পষ্ট হিসাব, যাতে ক্রেতা দরদাম না করে।",
        rawMaterialCost: "কাঁচামাল ও প্রাকৃতিক রঙের খরচ",
        artisanLaborHours: "কারিগরি শ্রমের সময় (ঘণ্টা)",
        hourlyWageBenchmark: "ঘণ্টাপ্রতি পারিশ্রমিক (₹৮০/ঘণ্টা)",
        giHeritagePremium: "জিআই ঐতিহ্য রয়্যালটি (+১৫%)",
        pricingSummaryTitle: "স্বচ্ছ মূল্য নির্ধারণের বিবরণ",
        totalDirectCost: "মোট উৎপাদন খরচ",
        recommendedRetail: "প্রস্তাবিত ন্যায্য খুচরা দাম",
        livingWageGuaranteed: "✓ ঘণ্টায় ₹৮০ সম্মানজনক মজুরি + ১৫% ঐতিহ্য সংরক্ষণ রয়্যালটি নিশ্চিত।",
        artisanProfileTitle: "কারিগর প্রোফাইল ও ঐতিহ্যবাহী ক্লাস্টার",
        artisanNameLabel: "কারিগরের নাম",
        craftLineageLabel: "হস্তশিল্পের বিশেষত্ব",
        recognizedClusterLabel: "স্বীকৃত ক্লাস্টার / অঞ্চল",
        phoneNumberLabel: "ফোন নম্বর (অ্যালার্টের জন্য)",
        updateProfileBtn: "প্রোফাইল আপডেট করুন",
        selectLanguageTitle: "আঞ্চলিক ভাষা নির্বাচন",
        chooseLangSubtitle: "কণ্ঠস্বর ও নির্দেশনার জন্য ভাষা পছন্দ করুন:",
        customAiTitle: "কাস্টম ভারতীয় ভাষা AI মডেল API",
        customAiSubtitle: "আপনার বাহ্যিক ভারতীয় ভাষা STT/TTS মডেলের ক্রেডিটস এখানে যুক্ত করুন:",
        saveAiCredentialsBtn: "API তথ্য সংরক্ষণ করুন",
        transparentCostPlus: "স্বচ্ছ উৎপাদন মূল্য মডেল",
        formulaCost: "উৎপাদন খরচ",
        formulaMaterial: "কাঁচামাল",
        formulaLabor: "শ্রম",
        formulaPackaging: "প্যাকিং",
        formulaTransport: "পরিবহন",
        formulaMargin: "মুনাফা",
        formulaExplanation: "AI শুধু সঠিক মূল্য প্রস্তাব করবে, চূড়ান্ত দাম নির্ধারণ আপনার সম্পূর্ণ নিজস্ব অধিকার।",
        adjustCostBreakdown: "খরচের হিসাব সামঞ্জস্য করুন:",
        artisanLaborValue: "কারিগরির শ্রমের মূল্য",
        ecoPackaging: "পরিবেশবান্ধব প্যাকিং",
        localFreight: "স্থানীয় পরিবহন খরচ",
        desiredMargin: "প্রত্যাশিত লাভ (%)",
        totalBaseCost: "মোট উৎপাদন ভিত্তি খরচ:",
        fairMarketRange: "ন্যায্য বাজার সীমা:",
        yourFinalPrice: "আপনার নির্ধারিত চূড়ান্ত দাম (₹):",
        lockPriceBtn: "এই দাম নিশ্চিত করুন",
        priceLockedToast: "তালিকার জন্য দাম নিশ্চিত করা হয়েছে!",
        listenHisabSummary: "হিসাবের বিবরণ শুনুন",
        dailyBusinessLedger: "দৈনিক খাতা",
        addVoiceLedgerTitle: "কথা বলে হিসাব যোগ করুন",
        holdSpeakEntry: "মাইক চেপে হিসাব বলুন",
        transcriptPlaceholder: "আপনার কথা এখানে দেখা যাবে...",
        incomeSalesLabel: "আয় / বিক্রি (₹)",
        expenseCostLabel: "ব্যয় / ক্রয় (₹)",
        entryDescLabel: "পণ্যের বিবরণ বা মন্তব্য",
        saveLedgerEntryBtn: "খাতায় সংরক্ষণ করুন",
        recentEntriesTitle: "সাম্প্রতিক হিসাবের তালিকা",
        noEntriesYet: "এখনো কোনো হিসাব যোগ করা হয়নি। উপরে মাইক চেপে রেকর্ড করুন।",
        ledgerEntrySavedToast: "হিসাব খাতায় সংরক্ষিত হয়েছে!",
        artisanCatalogTab: "কারিগর ডিজিটাল দোকান",
        aiSpaceStagerTab: "ঘরের সাজসজ্জা (AI ডেকর)",
        reelsToArtisanTab: "রিলস থেকে কারিগর সন্ধান",
        digitalStorefrontTitle: "আপনার ডিজিটাল শোরুম",
        shareStoreBtn: "সম্পূর্ণ দোকান শেয়ার করুন",
        shareCraftBtn: "শেয়ার",
        roomStagerTitle: "ঘরের সাজসজ্জা (AI স্পেস স্টেজার)",
        roomStagerSubtitle: "শহুরে বসার ঘরে খাঁটি হস্তশিল্প সাজিয়ে সরাসরি দেখুন:",
        selectRoomPreset: "ঘরের পরিবেশ নির্বাচন করুন:",
        roomModernLiving: "আধুনিক লিভিং রুম",
        roomCozyBedroom: "ঐতিহ্যবাহী বেডরুম",
        roomDiningWall: "খাবার ঘরের দেয়াল",
        renderStagedRoomBtn: "ঘরে সাজিয়ে দেখুন 🎨",
        reelsMatcherTitle: "রিলস থেকে কারিগর ভিজ্যুয়াল সন্ধান",
        reelsMatcherSubtitle: "সোশ্যাল মিডিয়ার ছবি দিয়ে সরাসরি ঐতিহ্যবাহী শিল্পীর সাথে সংযোগ স্থাপন করুন:",
        reelsDropzoneText: "ছবি এখানে টেনে আনুন বা ক্লিক করে আপলোড করুন",
        reelsMatchingBtn: "সঠিক কারিগর খুঁজুন 🔍",
        matchFoundTitle: "যাচাইকৃত ঐতিহ্যবাহী কারুশিল্প ক্লাস্টার:",
        enableCustomAiLabel: "বাহ্যিক ভারতীয় ভাষা AI মডেল ব্যবহার করুন",
        apiEndpointLabel: "STT/TTS API এন্ডপয়েন্ট",
        apiKeyLabel: "API টোকেন / Key",
        profileUpdatedToast: "প্রোফাইল আপডেট সম্পন্ন হয়েছে!",
        aiConfigSavedToast: "AI মডেল তথ্য সংরক্ষিত হয়েছে!"
      },

      hi: {
        appName: "कलासेतु AI",
        tagline: "कारीगरों का डिजिटल बिजनेस मैनेजर",
        listenTooltip: "आवाज़ में सुनें",
        onlineStatus: "ऑनलाइन · इंटरनेट चालू है",
        offlineStatus: "ऑफ़लाइन मोड · काम सुरक्षित सेव है",
        tabCataloger: "बोलकर लिस्टिंग",
        tabPricing: "सही दाम (मूल्य)",
        tabHisab: "दैनिक हिसाब-किताब",
        tabMarket: "दुकान व सजावट",
        tabSettings: "प्रोफ़ाइल व सेटिंग्स",
        tabFacilitator: "सहायता डेस्क (NGO)",
        capturePhoto: "शिल्प की साफ फोटो लें",
        cameraGuide: "प्राकृतिक रंग और शिल्प का असली रूप सुरक्षित रहेगा",
        holdToSpeak: "दबाकर रखें और सामान के बारे में बोलें",
        releaseToStop: "छोड़ते ही अपने आप लिस्टिंग बन जाएगी",
        generateDraft: "AI आपकी आवाज़ से लिस्टिंग बना रहा है...",
        listeningText: "सुन रहे हैं... अपनी भाषा में बोलें",
        speechPlaceholder: 'जैसे बोलें: "बगरू ब्लॉक प्रिंट का दुपट्टा है, 2.5 मीटर लंबा, नील का रंग, 2 दिन लगे"',
        craftName: "सामान का नाम",
        craftType: "शिल्प का प्रकार",
        materials: "इस्तेमाल हुआ सामान (सामग्री)",
        dimensions: "नाप / आकार",
        makingTime: "बनाने में लगा समय",
        careGuide: "रख-रखाव की सलाह",
        hindiDesc: "हिंदी में विवरण",
        englishDesc: "अंग्रेजी में विवरण (खरीदारों के लिए)",
        baseCostLabel: "लागत खर्च (सामग्री + मेहनत)",
        suggestedRange: "AI सुझाया गया सही दाम",
        confirmListingBtn: "लिस्टिंग पक्की करें (दुकान में जोड़ें)",
        shareWhatsappBtn: "व्हाट्सएप पर शेयर करें",
        artisanDecisionNote: "AI सिर्फ सुझाव देगा, अंतिम फैसला आपका होगा।",
        dailyHisabTitle: "आज का दैनिक हिसाब-किताब",
        hisabPrompt: 'जैसे बोलें: "आज 500 का रंग लिया और 2 दुपट्टे 3000 में बेचे"',
        recordExpenseIncome: "बोलकर आज का खर्च व कमाई दर्ज करें",
        incomeLabel: "आज की कुल बिक्री",
        expenseLabel: "आज का कुल खर्च",
        netProfitLabel: "आज का शुद्ध मुनाफा",
        spaceStagerTitle: "कमरे की सजावट (AI डेकोर)",
        spaceStagerDesc: "दीवार की फोटो डालें और देखें आपका शिल्प कैसा सजेगा",
        reelsSearchTitle: "रील्स-से-कारीगर खोज",
        reelsSearchDesc: "सोशल मीडिया का स्क्रीनशॉट डालकर असली कारीगर से जोड़ें",
        certifiedOrigin: "प्रमाणित जीआई क्लस्टर कारीगर",
        listenInstructions: "निर्देश आवाज़ में सुनें",
        colorPreservation: "रंग सुरक्षा चालू",
        cameraCenterTip: "सामान को चौकोर घेरे के अंदर रखें",
        tapToCapture: "फोटो खींचने या अपलोड करने के लिए टैप करें",
        studioLighting: "लाइट सुधारें",
        cleanBackdrop: "बैकग्राउंड साफ करें",
        retake: "दोबारा फोटो लें",
        step2Title: "बोलकर सामान का विवरण दें",
        voicePromptHelp: "सामान का नाम, कपड़ा/मिट्टी, नाप (लंबाई-चौड़ाई) और बनाने में लगा समय बोलें:",
        sampleVoiceDemo: "⚡ नमूना आवाज़ से ऑटो-भरें (डेमो)",
        step3Title: "AI तैयार डिजिटल लिस्टिंग",
        reviewDraft: "पुष्टि बाकी",
        authenticityConfirmation: "सत्यता प्रमाणीकरण (कारीगर द्वारा पुष्टि):",
        genuineHandcrafted: "यह 100% हस्तनिर्मित (हाथ का बना) है",
        belongsToGiCluster: "भौगोलिक संकेतक (GI Tag) क्लस्टर से संबद्ध है",
        calculatePriceBtn: "सही दाम का गणित निकालें (Cost-Plus) →",
        approveListingBtn: "लिस्टिंग पक्की करें (दुकान में जोड़ें) ✓",
        listenPricingBreakdown: "दाम का गणित आवाज़ में सुनें",
        explainablePricingTitle: "पारदर्शी दाम कैलकुलेटर",
        pricingFormulaSubtitle: "हर एक रुपये का हिसाब साफ, ताकि खरीदार मोलभाव न करे।",
        rawMaterialCost: "सामग्री व प्राकृतिक रंग की लागत",
        artisanLaborHours: "कारीगरी में लगे घंटे",
        hourlyWageBenchmark: "न्यूनतम सम्मानजनक मजदूरी (₹80/घंटा)",
        giHeritagePremium: "जीआई विरासत रॉयल्टी (+15%)",
        pricingSummaryTitle: "पारदर्शी मूल्य निर्धारण विवरण",
        totalDirectCost: "कुल उत्पादन लागत",
        recommendedRetail: "सुझाया गया सही खुदरा दाम",
        livingWageGuaranteed: "✓ ₹80/घंटे की न्यूनतम सम्मानजनक मजदूरी + 15% विरासत संरक्षण रॉयल्टी सुनिश्चित।",
        artisanProfileTitle: "कारीगर प्रोफ़ाइल व क्लस्टर पहचान",
        artisanNameLabel: "कारीगर का नाम",
        craftLineageLabel: "शिल्प व विरासत",
        recognizedClusterLabel: "क्लस्टर / राज्य",
        phoneNumberLabel: "फ़ोन नंबर (SMS अलर्ट हेतु)",
        updateProfileBtn: "प्रोफ़ाइल अपडेट करें",
        selectLanguageTitle: "भाषा का चुनाव",
        chooseLangSubtitle: "अपनी पसंदीदा क्षेत्रीय भाषा चुनें (Voice & UI):",
        customAiTitle: "AI मॉडल क्रेडिट्स व STT/TTS API",
        customAiSubtitle: "यदि आपके पास 6-9 भारतीय भाषाओं वाले STT/TTS AI मॉडल के क्रेडिट्स हैं, तो यहाँ API जोड़ें:",
        saveAiCredentialsBtn: "API सेटिंग्स सुरक्षित करें",
        transparentCostPlus: "पारदर्शी लागत मॉडल",
        formulaCost: "लागत",
        formulaMaterial: "सामग्री",
        formulaLabor: "मेहनत",
        formulaPackaging: "पैकिंग",
        formulaTransport: "किराया",
        formulaMargin: "मुनाफा",
        formulaExplanation: "AI सिर्फ उचित मूल्य का सुझाव देगा, अंतिम दाम तय करना पूरी तरह आपके हाथ में है।",
        adjustCostBreakdown: "खर्चे का विवरण भरें:",
        artisanLaborValue: "कारीगर की मेहनत (मजदूरी)",
        ecoPackaging: "पैकिंग सामग्री (सुरक्षित डिब्बा)",
        localFreight: "परिवहन / ढुलाई खर्च",
        desiredMargin: "अपेक्षित मुनाफा (%)",
        totalBaseCost: "कुल आधार लागत (Base Cost):",
        fairMarketRange: "उचित बाजार सीमा:",
        yourFinalPrice: "आपका अंतिम तय किया गया दाम (₹):",
        lockPriceBtn: "यह दाम सुरक्षित करें",
        priceLockedToast: "दाम सुरक्षित कर दिया गया!",
        listenHisabSummary: "हिसाब-किताब आवाज़ में सुनें",
        dailyBusinessLedger: "दैनिक बहीखाता",
        addVoiceLedgerTitle: "बोलकर हिसाब जोड़ें",
        holdSpeakEntry: "माइक दबाकर हिसाब बोलें",
        transcriptPlaceholder: "आपकी बोली गई बात यहाँ दिखेगी...",
        incomeSalesLabel: "कमाई / बिक्री (₹)",
        expenseCostLabel: "खर्च / खरीदारी (₹)",
        entryDescLabel: "सामान या ग्राहक का विवरण",
        saveLedgerEntryBtn: "खाते में सेव करें",
        recentEntriesTitle: "हालिया लेन-देन सूची",
        noEntriesYet: "अभी कोई लेन-देन दर्ज नहीं है। ऊपर माइक दबाकर बोलें।",
        ledgerEntrySavedToast: "लेन-देन खाते में जुड़ गया!",
        artisanCatalogTab: "कारीगर डिजिटल दुकान",
        aiSpaceStagerTab: "कमरे की सजावट (AI Decor)",
        reelsToArtisanTab: "रील्स-से-कारीगर खोज",
        digitalStorefrontTitle: "आपकी लाइव डिजिटल दुकान",
        shareStoreBtn: "पूरी दुकान शेयर करें",
        shareCraftBtn: "शेयर",
        roomStagerTitle: "कमरे की सजावट (AI रूम स्टेजर)",
        roomStagerSubtitle: "शहरी घरों के कमरों में अपना शिल्प सजाकर देखें:",
        selectRoomPreset: "कमरे का प्रकार चुनें:",
        roomModernLiving: "आधुनिक बैठक (Living Room)",
        roomCozyBedroom: "पारंपरिक बेडरूम",
        roomDiningWall: "डाइनिंग हॉल की दीवार",
        renderStagedRoomBtn: "कमरे में सजाकर देखें 🎨",
        reelsMatcherTitle: "रील्स-से-कारीगर विज़ुअल खोज",
        reelsMatcherSubtitle: "सोशल मीडिया की फोटो से असली शिल्प क्लस्टर खोजें:",
        reelsDropzoneText: "इंस्टाग्राम या सोशल मीडिया स्क्रीनशॉट यहाँ डालें",
        reelsMatchingBtn: "असली कारीगर खोजें 🔍",
        matchFoundTitle: "प्रमाणित पारंपरिक क्लस्टर पहचान:",
        enableCustomAiLabel: "कस्टम AI मॉडल API इस्तेमाल करें",
        apiEndpointLabel: "API एंडपॉइंट URL",
        apiKeyLabel: "API Key / टोकन",
        profileUpdatedToast: "प्रोफ़ाइल सुरक्षित हो गई!",
        aiConfigSavedToast: "AI मॉडल सेटिंग्स सुरक्षित कर ली गईं!"
      },

      mr: {
        appName: "कलासेतू AI",
        tagline: "कारागिरांचा डिजिटल व्यवसाय व्यवस्थापक",
        listenTooltip: "आवाजात ऐका",
        onlineStatus: "ऑनलाइन · इंटरनेट सुरू आहे",
        offlineStatus: "ऑफलाइन मोड · सुरक्षित साठवले",
        tabCataloger: "आवाजातून कॅटलॉग",
        tabPricing: "योग्य किंमत",
        tabHisab: "हिशोब-किताब",
        tabMarket: "दुकान व सजावट",
        tabSettings: "प्रोफाइल व सेटिंग",
        capturePhoto: "कलेचा फोटो काढा",
        cameraGuide: "नैसर्गिक रंग आणि मूळ आकार सुरक्षित राहतील",
        holdToSpeak: "बटण दाबून ठेवा आणि बोला",
        releaseToStop: "सोडल्यावर लगेच लिस्टिंग तयार होईल",
        generateDraft: "AI आपल्या आवाजातून लिस्टिंग बनवत आहे...",
        listeningText: "ऐकत आहोत... आपल्या भाषेत बोला",
        speechPlaceholder: 'उदा. बोला: "पैठणी साडी, रेशमी धागा, नैसर्गिक रंग, ४ दिवस लागले"',
        craftName: "वस्तूचे नाव",
        craftType: "हस्तकला प्रकार",
        materials: "वापरलेले साहित्य",
        dimensions: "आकार / लांबी",
        makingTime: "तयार करण्यास लागलेले दिवस",
        careGuide: "काळजी घेण्याच्या सूचना",
        hindiDesc: "प्रादेशिक भाषेत वर्णन",
        englishDesc: "इंग्रजी वर्णन (ग्राहकांसाठी)",
        baseCostLabel: "एकूण खर्च (साहित्य + मजुरी)",
        suggestedRange: "AI सुचवलेली योग्य किंमत",
        confirmListingBtn: "कॅटलॉगमध्ये जोडा",
        shareWhatsappBtn: "व्हॉट्सॲपवर पाठवा",
        artisanDecisionNote: "AI फक्त सल्ला देईल, अंतिम निर्णय तुमचाच असेल.",
        dailyHisabTitle: "आजचा दैनिक हिशोब-किताब",
        hisabPrompt: 'उदा: "आज ५०० रुपयांचे रंग घेतले आणि २ वस्तू ३००० ला विकल्या"',
        recordExpenseIncome: "बोलून आजचा खर्च व कमाई नोंदवा",
        incomeLabel: "आजची एकूण विक्री",
        expenseLabel: "आजचा एकूण खर्च",
        netProfitLabel: "आजचा निव्वळ नफा",
        spaceStagerTitle: "खोली सजावट (AI डेकोर)",
        spaceStagerDesc: "भिंतीचा फोटो अपलोड करून कलाकृती सजवून पहा",
        reelsSearchTitle: "रील्स-ते-कारागीर शोध",
        reelsSearchDesc: "सोशल मीडिया स्क्रीनशॉटवरून मूळ कारागीर शोधा",
        certifiedOrigin: "प्रमाणित जीआय क्लस्टर कारागीर",
        listenInstructions: "सूचना आवाजात ऐका",
        colorPreservation: "रंग सुरक्षा चालू",
        cameraCenterTip: "वस्तू चौकटीच्या मध्यभागी ठेवा",
        tapToCapture: "फोटो काढण्यासाठी किंवा अपलोड करण्यासाठी टॅप करा",
        studioLighting: "लाईट सुधारा",
        cleanBackdrop: "पार्श्वभूमी स्वच्छ करा",
        retake: "पुन्हा फोटो घ्या",
        step2Title: "वस्तूचे वर्णन बोलून सांगा",
        voicePromptHelp: "वस्तूचे नाव, कापड/साहित्य आणि लागणारा वेळ बोला:",
        sampleVoiceDemo: "⚡ नमुना आवाजाने भरा (डेमो)",
        step3Title: "AI द्वारे तयार लिस्टिंग",
        reviewDraft: "तपासा",
        authenticityConfirmation: "सत्यता पडताळणी:",
        genuineHandcrafted: "१००% अस्सल हस्तनिर्मित वस्तू",
        belongsToGiCluster: "नोंदणीकृत जीआय क्लस्टरशी संबंधित",
        calculatePriceBtn: "योग्य किंमत काढा (Cost-Plus) →",
        approveListingBtn: "कॅटलॉगमध्ये जोडा ✓",
        listenPricingBreakdown: "किंमतीचे गणित ऐका",
        explainablePricingTitle: "पारदर्शक किंमत कॅल्क्युलेटर",
        pricingFormulaSubtitle: "प्रत्येक रुपयाचा स्पष्ट हिशोब, जेणेकरून ग्राहक घासाघिस करणार नाही.",
        rawMaterialCost: "कच्चा माल व रंगांचा खर्च",
        artisanLaborHours: "कारागिरीचे तास",
        hourlyWageBenchmark: "किमान मजुरी (₹८०/तास)",
        giHeritagePremium: "जीआय वारसा रॉयल्टी (+१५%)",
        pricingSummaryTitle: "किंमत तपशील",
        totalDirectCost: "एकूण उत्पादन खर्च",
        recommendedRetail: "सुचवलेली योग्य किंमत",
        livingWageGuaranteed: "✓ ₹८०/तास सन्मानजनक मजुरी + १५% रॉयल्टी निश्चित.",
        artisanProfileTitle: "कारागीर प्रोफाइल व वारसा",
        artisanNameLabel: "कारागिराचे नाव",
        craftLineageLabel: "हस्तकला प्रकार",
        recognizedClusterLabel: "क्लस्टर / राज्य",
        phoneNumberLabel: "फोन नंबर",
        updateProfileBtn: "प्रोफाइल अपडेट करा",
        selectLanguageTitle: "भाषा निवडा",
        chooseLangSubtitle: "आपली आवडती भाषा निवडा:",
        customAiTitle: "AI मॉडेल API सेटिंग्ज",
        customAiSubtitle: "आपल्या भारतीय भाषेतील AI मॉडेलचे क्रेडीट्स येथे जोडा:",
        saveAiCredentialsBtn: "सेटिंग्ज जतन करा",
        transparentCostPlus: "पारदर्शक उत्पादन किंमत मॉडेल",
        formulaCost: "उत्पादन खर्च",
        formulaMaterial: "कच्चा माल",
        formulaLabor: "श्रम",
        formulaPackaging: "पॅकिंग",
        formulaTransport: "वाहतूक",
        formulaMargin: "नफा",
        formulaExplanation: "AI फक्त योग्य किंमतीचा सल्ला देईल, अंतिम किंमत ठरवणे पूर्णपणे तुमच्या हातात आहे.",
        adjustCostBreakdown: "खर्चाचा तपशील बदला:",
        artisanLaborValue: "कारागिराचे कष्ट (मजुरी)",
        ecoPackaging: "सुरक्षित पॅकिंग",
        localFreight: "स्थानिक वाहतूक खर्च",
        desiredMargin: "अपेक्षित नफा (%)",
        totalBaseCost: "एकूण मूळ उत्पादन खर्च:",
        fairMarketRange: "योग्य बाजार भाव मर्यादा:",
        yourFinalPrice: "तुमची ठरवलेली अंतिम किंमत (₹):",
        lockPriceBtn: "ही किंमत निश्चित करा",
        priceLockedToast: "किंमत निश्चित करण्यात आली!",
        listenHisabSummary: "हिशेब आवाजात ऐका",
        dailyBusinessLedger: "दैनंदिन हिशेबवही",
        addVoiceLedgerTitle: "बोलून हिशेब जोडा",
        holdSpeakEntry: "माइक दाबून हिशेब सांगा",
        transcriptPlaceholder: "तुमचे शब्द येथे दिसतील...",
        incomeSalesLabel: "कमाई / विक्री (₹)",
        expenseCostLabel: "खर्च / खरेदी (₹)",
        entryDescLabel: "तपशील किंवा ग्राहक माहिती",
        saveLedgerEntryBtn: "वहीत नोंदवा",
        recentEntriesTitle: "अलीकडील व्यवहार यादी",
        noEntriesYet: "अजून कोणतीही नोंद नाही. वर माइक दाबून बोला.",
        ledgerEntrySavedToast: "नोंद सुरक्षित केली गेली!",
        artisanCatalogTab: "कारागीर डिजिटल दुकान",
        aiSpaceStagerTab: "खोली सजावट (AI Decor)",
        reelsToArtisanTab: "रील्सवरून कारागीर शोध",
        digitalStorefrontTitle: "तुमचे डिजिटल दालन",
        shareStoreBtn: "संपूर्ण दुकान शेअर करा",
        shareCraftBtn: "शेअर",
        roomStagerTitle: "खोली सजावट (AI रूम स्टेजर)",
        roomStagerSubtitle: "शहरातील घरांच्या बैठकीत तुमची कलाकृती सजवून पहा:",
        selectRoomPreset: "खोलीचा प्रकार निवडा:",
        roomModernLiving: "आधुनिक दिवाणखाना",
        roomCozyBedroom: "पारंपारिक बेडरूम",
        roomDiningWall: "डायनिंग हॉल भिंत",
        renderStagedRoomBtn: "खोलीत सजवून पहा 🎨",
        reelsMatcherTitle: "रील्सवरून कारागीर शोध",
        reelsMatcherSubtitle: "सोशल मीडिया फोटोवरून थेट अस्सल कारागीर शोधा:",
        reelsDropzoneText: "सोशल मीडिया स्क्रीनशॉट येथे टाका किंवा अपलोड करा",
        reelsMatchingBtn: "अस्सल कारागीर शोधा 🔍",
        matchFoundTitle: "प्रमाणित पारंपारिक क्लस्टर ओळख:",
        enableCustomAiLabel: "कस्टम AI मॉडेल API वापरा",
        apiEndpointLabel: "API एंडपॉइंट URL",
        apiKeyLabel: "API की / टोकन",
        profileUpdatedToast: "प्रोफाइल अपडेट झाली!",
        aiConfigSavedToast: "AI मॉडेल सेटिंग्ज सुरक्षित झाल्या!"
      },

      ta: {
        appName: "கலாசேது AI",
        tagline: "கைவினைஞர்களுக்கான டிஜிட்டல் வணிக மேலாளர்",
        listenTooltip: "குரலில் கேளுங்கள்",
        onlineStatus: "ஆன்லைன் · தயாராக உள்ளது",
        offlineStatus: "ஆஃப்லைன் · உள்ளூரில் சேமிக்கப்பட்டது",
        tabCataloger: "குரல் பட்டியல்",
        tabPricing: "நியாய விலை",
        tabHisab: "வரவு-செலவு கணக்கு",
        tabMarket: "அங்காடி & அலங்காரம்",
        tabSettings: "சுயவிவரம் & அமைப்புகள்",
        capturePhoto: "பொருளின் புகைப்படம் எடுக்கவும்",
        cameraGuide: "இயற்கை வண்ணங்களும் வடிவங்களும் பாதுகாக்கப்படும்",
        holdToSpeak: "அழுத்திப் பிடித்து கைவினை விவரம் பேசுங்கள்",
        releaseToStop: "விட்டதும் டிஜிட்டல் பட்டியல் தயாராகும்",
        generateDraft: "AI உங்கள் குரலை கொண்டு பட்டியல் உருவாக்குகிறது...",
        listeningText: "கேட்கிறது... உங்கள் மொழியில் பேசுங்கள்",
        speechPlaceholder: 'உதாரணம்: "காஞ்சிபுரம் பட்டுப் புடவை, தூய ஜரிகை, 5 நாட்கள் ஆனது"',
        craftName: "பொருளின் பெயர்",
        craftType: "கைவினை வகை",
        materials: "பயன்படுத்தப்பட்ட பொருட்கள்",
        dimensions: "அளவு / நீளம்",
        makingTime: "தயாரிக்க ஆன நாட்கள்",
        careGuide: "பராமரிப்பு குறிப்புகள்",
        hindiDesc: "உள்ளூர் மொழி விளக்கம்",
        englishDesc: "ஆங்கில விளக்கம் (வாங்குபவர்களுக்கு)",
        baseCostLabel: "மொத்த உற்பத்தி செலவு",
        suggestedRange: "AI பரிந்துரைக்கும் நியாய விலை",
        confirmListingBtn: "பட்டியலில் சேர்க்கவும்",
        shareWhatsappBtn: "வாட்ஸ்அப்பில் பகிரவும்",
        artisanDecisionNote: "AI பரிந்துரைக்கும், ஆனால் இறுதி முடிவு உங்களுடையது.",
        dailyHisabTitle: "இன்றைய வரவு-செலவு கணக்கு",
        hisabPrompt: 'உதாரணம்: "ரூ. 500 மூலப்பொருள் வாங்கி 2 புடவைகளை ரூ. 4000க்கு விற்றேன்"',
        recordExpenseIncome: "பேசி இன்றைய வரவு செலவை பதிவு செய்யவும்",
        incomeLabel: "இன்றைய மொத்த விற்பனை",
        expenseLabel: "இன்றைய மொத்த செலவு",
        netProfitLabel: "இன்றைய நிகர லாபம்",
        spaceStagerTitle: "அறை அலங்காரக் காட்சி (AI ஸ்டேஜர்)",
        spaceStagerDesc: "சுவர் புகைப்படத்தில் உங்கள் கைவினை எப்படி பொருந்துகிறது என்று பாருங்கள்",
        reelsSearchTitle: "ரீல்ஸ்-மூலம்-கைவினைஞர் தேடல்",
        reelsSearchDesc: "இன்ஸ்டாகிராம் புகைப்படத்தை வைத்து நேரடி கைவினைஞரைத் தேடுங்கள்",
        certifiedOrigin: "அங்கீகரிக்கப்பட்ட GI கிளஸ்டர் கைவினைஞர்",
        listenInstructions: "வழிமுறைகளை கேளுங்கள்",
        colorPreservation: "வண்ண பாதுகாப்பு चालू",
        cameraCenterTip: "பொருளை சட்டத்தின் நடுவில் வைக்கவும்",
        tapToCapture: "புகைப்படம் எடுக்க தட்டவும்",
        studioLighting: "வெளிச்சத்தை மேம்படுத்து",
        cleanBackdrop: "பின்னணியை சுத்தப்படுத்து",
        retake: "மீண்டும் எடுக்கவும்",
        step2Title: "பொருளைப் பற்றி குரலில் சொல்லுங்கள்",
        voicePromptHelp: "பொருளின் பெயர், மூலப்பொருள் மற்றும் தயாரிப்பு நேரத்தை சொல்லுங்கள்:",
        sampleVoiceDemo: "⚡ மாதிரி குரல் மூலம் சோதிக்கவும்",
        step3Title: "AI உருவாக்கிய பட்டியல்",
        reviewDraft: "சரிபார்க்கவும்",
        authenticityConfirmation: "உண்மைத்தன்மை சான்றிதழ்:",
        genuineHandcrafted: "100% உண்மையான கைவினைப் பொருள்",
        belongsToGiCluster: "பதிவுசெய்யப்பட்ட GI கிளஸ்டரைச் சேர்ந்தது",
        calculatePriceBtn: "நியாய விலையை கணக்கிடுங்கள் →",
        approveListingBtn: "பட்டியலில் உறுதிப்படுத்தவும் ✓",
        listenPricingBreakdown: "விலை கணக்கீட்டை கேளுங்கள்",
        explainablePricingTitle: "நியாய விலை கால்குலேட்டர்",
        pricingFormulaSubtitle: "ஒவ்வொரு ரூபாய்க்கும் தெளிவான கணக்கு.",
        rawMaterialCost: "மூலப்பொருள் & சாயம் செலவு",
        artisanLaborHours: "கைவினை உழைப்பு நேரம்",
        hourlyWageBenchmark: "மணிக்கு ஊதியம் (₹80/மணி)",
        giHeritagePremium: "GI பாரம்பரிய ராயல்டி (+15%)",
        pricingSummaryTitle: "விலை நிர்ணய விவரம்",
        totalDirectCost: "மொத்த உற்பத்தி செலவு",
        recommendedRetail: "பரிந்துரைக்கப்பட்ட சில்லறை விலை",
        livingWageGuaranteed: "✓ மணிக்கு ₹80 கண்ணியமான ஊதியம் + 15% ராயல்டி உறுதி.",
        artisanProfileTitle: "கைவினைஞர் சுயவிவரம்",
        artisanNameLabel: "கைவினைஞர் பெயர்",
        craftLineageLabel: "கைவினை சிறப்பு",
        recognizedClusterLabel: "கிளஸ்டர் / மாநிலம்",
        phoneNumberLabel: "தொலைபேசி எண்",
        updateProfileBtn: "சுயவிவரத்தை புதுப்பிக்கவும்",
        selectLanguageTitle: "மொழியைத் தேர்ந்தெடுக்கவும்",
        chooseLangSubtitle: "உங்களுக்கு விருப்பமான மொழியைத் தேர்வு செய்யவும்:",
        customAiTitle: "AI மாதிரி API அமைப்புகள்",
        customAiSubtitle: "உங்கள் இந்திய மொழி AI மாதிரியின் விவரங்களை உள்ளிடவும்:",
        saveAiCredentialsBtn: "அமைப்புகளை சேமிக்கவும்",
        transparentCostPlus: "வெளிப்படையான உற்பத்தி விலை மாதிரி",
        formulaCost: "செலவு",
        formulaMaterial: "பொருட்கள்",
        formulaLabor: "உழைப்பு",
        formulaPackaging: "பேக்கிங்",
        formulaTransport: "போக்குவரத்து",
        formulaMargin: "லாபம்",
        formulaExplanation: "AI நியாயமான விலையை மட்டுமே பரிந்துரைக்கும், இறுதி விலை உங்கள் முடிவே ஆகும்.",
        adjustCostBreakdown: "செலவு விவரங்களை மாற்றவும்:",
        artisanLaborValue: "கைவினைஞரின் உழைப்பு மதிப்பு",
        ecoPackaging: "பாதுகாப்பான பேக்கிங்",
        localFreight: "உள்ளூர் போக்குவரத்து செலவு",
        desiredMargin: "எதிர்பார்க்கும் லாபம் (%)",
        totalBaseCost: "மொத்த அடிப்படை தயாரிப்பு செலவு:",
        fairMarketRange: "நியாயமான சந்தை விலை வரம்பு:",
        yourFinalPrice: "உங்கள் இறுதி விற்பனை விலை (₹):",
        lockPriceBtn: "விலையை உறுதிப்படுத்துங்கள்",
        priceLockedToast: "விலை உறுதிப்படுத்தப்பட்டது!",
        listenHisabSummary: "கணக்கு விவரங்களை கேட்கவும்",
        dailyBusinessLedger: "தினசரி கணக்கு புத்தகம்",
        addVoiceLedgerTitle: "குரல் மூலம் கணக்கை சேர்க்கவும்",
        holdSpeakEntry: "மைக்கை அழுத்தி கணக்கை பேசவும்",
        transcriptPlaceholder: "நீங்கள் பேசியவை இங்கே தோன்றும்...",
        incomeSalesLabel: "வருமானம் / விற்பனை (₹)",
        expenseCostLabel: "செலவு / கொள்முதல் (₹)",
        entryDescLabel: "விவரம் அல்லது குறிப்பு",
        saveLedgerEntryBtn: "கணக்கில் சேமிக்கவும்",
        recentEntriesTitle: "சமீபத்திய பரிவர்த்தனைகள்",
        noEntriesYet: "இன்னும் கணக்கு எதுவும் பதியப்படவில்லை. மேலே மைக்கை அழுத்தி பேசவும்.",
        ledgerEntrySavedToast: "கணக்கு வெற்றிகரமாக சேமிக்கப்பட்டது!",
        artisanCatalogTab: "கைவினைஞர் டிஜிட்டல் கடை",
        aiSpaceStagerTab: "அறை அலங்காரம் (AI Decor)",
        reelsToArtisanTab: "ரீல்ஸ்-மூலம்-கைவினைஞர் தேடல்",
        digitalStorefrontTitle: "உங்கள் டிஜிட்டல் அங்காடி",
        shareStoreBtn: "முழு கடையையும் பகிரவும்",
        shareCraftBtn: "பகிர்",
        roomStagerTitle: "அறை அலங்காரம் (AI ஸ்பேஸ் ஸ்டேஜர்)",
        roomStagerSubtitle: "நவீன வாழ்க்கை அறைகளில் உங்கள் பாரம்பரிய கைவினைப் பொருட்களை வைத்துப் பாருங்கள்:",
        selectRoomPreset: "அறை அமைப்பைத் தேர்ந்தெடுக்கவும்:",
        roomModernLiving: "நவீன வாழ்க்கை அறை",
        roomCozyBedroom: "பாரம்பரிய படுக்கையறை",
        roomDiningWall: "உணவு அறை சுவர்",
        renderStagedRoomBtn: "அறையில் வைத்துப் பார்க்க 🎨",
        reelsMatcherTitle: "ரீல்ஸ் மூலம் கைவினைஞர் தேடல்",
        reelsMatcherSubtitle: "சமூக ஊடக படங்களிலிருந்து உண்மையான கைவினைஞர்களைக் கண்டறியவும்:",
        reelsDropzoneText: "திரைப்படத்தை இங்கே இழுக்கவும் அல்லது பதிவேற்றவும்",
        reelsMatchingBtn: "உண்மையான கைவினைஞரைக் கண்டுபிடி 🔍",
        matchFoundTitle: "சான்றளிக்கப்பட்ட பாரம்பரிய கிளஸ்டர்:",
        enableCustomAiLabel: "வெளிப்புற இந்திய மொழி AI மாதிரியைப் பயன்படுத்தவும்",
        apiEndpointLabel: "API URL முடிவுப்புள்ளி",
        apiKeyLabel: "API விசை / டோக்கன்",
        profileUpdatedToast: "சுயவிவரம் புதுப்பிக்கப்பட்டது!",
        aiConfigSavedToast: "AI அமைப்புகள் சேமிக்கப்பட்டன!"
      },

      te: {
        appName: "కళాసేతు AI",
        tagline: "చేతివృత్తుల వారి డిజిటల్ వ్యాపార సారథి",
        listenTooltip: "వాయిస్ లో వినండి",
        onlineStatus: "ఆన్‌లైన్ · సింక్ సిద్ధం",
        offlineStatus: "ఆఫ్‌లైన్ మోడ్ · భద్రపరచబడింది",
        tabCataloger: "వాయిస్ క్యాటలాగ్",
        tabPricing: "సరసమైన ధర",
        tabHisab: "రోజువారీ లెక్కలు (హిసాబ్)",
        tabMarket: "షాప్ & డెకోర్",
        tabSettings: "ప్రొఫైల్ & సెట్టింగ్‌లు",
        capturePhoto: "కళాఖండం ఫోటో తీయండి",
        cameraGuide: "సహజ రంగులు మరియు రూపం సురక్షితంగా ఉంటాయి",
        holdToSpeak: "బటన్ నొక్కి పట్టుకుని మాట్లాడండి",
        releaseToStop: "వదిలేయగానే క్యాటలాగ్ సిద్ధమవుతుంది",
        generateDraft: "AI మీ వాయిస్ తో క్యాటలాగ్ రూపొందిస్తోంది...",
        listeningText: "వింటున్నాము... మీ భాషలో మాట్లాడండి",
        speechPlaceholder: 'ఉదాహరణ: "పోచంపల్లి ఇక్కత్ చీర, సహజ రంగులు, 3 రోజులు పట్టింది"',
        craftName: "వస్తువు పేరు",
        craftType: "చేతిపని విభాగం",
        materials: "ఉపయోగించిన వస్తువులు",
        dimensions: "కొలతలు / పరిమాణం",
        makingTime: "తయారీకి పట్టిన సమయం",
        careGuide: "సంరక్షణ సలహాలు",
        hindiDesc: "స్థానిక భాషా వివరణ",
        englishDesc: "ఇంగ్లీష్ వివరణ (కొనుగోలుదారుల కోసం)",
        baseCostLabel: "మొత్తం తయారీ ఖర్చు",
        suggestedRange: "AI సూచించిన సరసమైన ధర",
        confirmListingBtn: "క్యాటలాగ్ లో చేర్చండి",
        shareWhatsappBtn: "వాట్సాప్ లో పంపండి",
        artisanDecisionNote: "AI సూచన మాత్రమే ఇస్తుంది, తుది నిర్ణయం మీదే.",
        dailyHisabTitle: "నేటి రోజువారీ లెక్కలు (హిసాబ్-కితాబ్)",
        hisabPrompt: 'ఉదాహరణ: "నేడు 500 రంగులకు ఖర్చు చేసి 2 చీరలు 3500 కి అమ్మాను"',
        recordExpenseIncome: "మాట్లాడి ఖర్చులు మరియు ఆదాయాన్ని నమోదు చేయండి",
        incomeLabel: "నేటి మొత్తం అమ్మకాలు",
        expenseLabel: "నేటి మొత్తం ఖర్చులు",
        netProfitLabel: "నేటి నికర లాభం",
        spaceStagerTitle: "గది అలంకరణ (AI డెకోర్)",
        spaceStagerDesc: "గోడ ఫోటోతో మీ కళ ఎలా అలంకరించబడుతుందో చూడండి",
        reelsSearchTitle: "రీల్స్ నుండి చేతివృత్తుల శోధన",
        reelsSearchDesc: "సోషల్ మీడియా స్క్రీన్‌షాట్ నుండి నిజమైన కళాకారుడిని కలవండి",
        certifiedOrigin: "ధృవీకరించబడిన GI క్లస్టర్ కళాకారుడు",
        listenInstructions: "సూచనలను వినండి",
        colorPreservation: "రంగుల రక్షణ",
        cameraCenterTip: "వస్తువును ఫ్రేమ్ మధ్యలో ఉంచండి",
        tapToCapture: "ఫోటో తీయడానికి ట్యాప్ చేయండి",
        studioLighting: "లైటింగ్ మెరుగుపరచండి",
        cleanBackdrop: "బ్యాక్‌గ్రౌండ్ క్లీన్ చేయండి",
        retake: "మళ్లీ ఫోటో తీయండి",
        step2Title: "కళాఖండం వివరాలు మాట్లాడండి",
        voicePromptHelp: "పేరు, పదార్థం మరియు తయారీ సమయం చెప్పండి:",
        sampleVoiceDemo: "⚡ నమూనా వాయిస్ తో పరీక్షించండి",
        step3Title: "AI సిద్ధం చేసిన క్యాటలాగ్",
        reviewDraft: "సరిచూసుకోండి",
        authenticityConfirmation: "ప్రామాణికత ధృవీకరణ:",
        genuineHandcrafted: "100% అసలైన చేతిపని వస్తువు",
        belongsToGiCluster: "రిజిస్టర్డ్ GI క్లస్టర్ కు చెందినది",
        calculatePriceBtn: "సరసమైన ధరను లెక్కించండి →",
        approveListingBtn: "క్యాటలాగ్ లో చేర్చండి ✓",
        listenPricingBreakdown: "ధర వివరణను వినండి",
        explainablePricingTitle: "సరసమైన ధర కాలిక్యులేటర్",
        pricingFormulaSubtitle: "ప్రతి రూపాయికి స్పష్టమైన లెక్క.",
        rawMaterialCost: "ముడి పదార్థం & రంగుల ఖర్చు",
        artisanLaborHours: "చేతిపనికి పట్టిన సమయం",
        hourlyWageBenchmark: "గంటకు వేతనం (₹80/గం)",
        giHeritagePremium: "GI వారసత్వ రాయల్టీ (+15%)",
        pricingSummaryTitle: "ధర నిర్ధారణ వివరాలు",
        totalDirectCost: "మొత్తం తయారీ ఖర్చు",
        recommendedRetail: "సిఫార్సు చేయబడిన రిటైల్ ధర",
        livingWageGuaranteed: "✓ గంటకు ₹80 కనీస వేతనం + 15% రాయల్టీ ఖాయం.",
        artisanProfileTitle: "కళాకారుడి ప్రొఫైల్",
        artisanNameLabel: "కళాకారుడి పేరు",
        craftLineageLabel: "చేతిపని ప్రత్యేకత",
        recognizedClusterLabel: "క్లస్టర్ / ప్రాంతం",
        phoneNumberLabel: "ఫోన్ నంబర్",
        updateProfileBtn: "ప్రొఫైల్ నవీకరించండి",
        selectLanguageTitle: "భాషను ఎంచుకోండి",
        chooseLangSubtitle: "మీకు కావలసిన భాషను ఎంచుకోండి:",
        customAiTitle: "AI మోడల్ సెట్టింగ్‌లు",
        customAiSubtitle: "మీ భారతీయ భాషా AI క్రెడిట్‌లను ఇక్కడ నమోదు చేయండి:",
        saveAiCredentialsBtn: "సెట్టింగ్‌లను సేవ్ చేయండి",
        transparentCostPlus: "పారదర్శక వ్యయ నమూనా",
        formulaCost: "వ్యయం",
        formulaMaterial: "ముడి సరుకు",
        formulaLabor: "శ్రమ",
        formulaPackaging: "ప్యాకింగ్",
        formulaTransport: "రవాణా",
        formulaMargin: "లాభం",
        formulaExplanation: "AI కేవలం సరసమైన ధరను సూచిస్తుంది, తుది ధర మీ నిర్ణయమే.",
        adjustCostBreakdown: "ఖర్చు వివరాలను సర్దుబాటు చేయండి:",
        artisanLaborValue: "చేతివృత్తి కళాకారుల శ్రమ విలువ",
        ecoPackaging: "సురక్షిత ప్యాకింగ్",
        localFreight: "స్థానిక రవాణా ఖర్చు",
        desiredMargin: "ఆశించిన లాభం (%)",
        totalBaseCost: "మొత్తం ఉత్పత్తి మూల వ్యయం:",
        fairMarketRange: "సరసమైన మార్కెట్ ధర పరిధి:",
        yourFinalPrice: "మీరు నిర్ణయించిన తుది ధర (₹):",
        lockPriceBtn: "ఈ ధరను ఖరారు చేయండి",
        priceLockedToast: "ధర ఖరారు చేయబడింది!",
        listenHisabSummary: "ఖర్చుల వివరాలు వినండి",
        dailyBusinessLedger: "రోజువారీ లెక్కల పుస్తకం",
        addVoiceLedgerTitle: "మాట్లాడి లెక్కను నమోదు చేయండి",
        holdSpeakEntry: "మైక్ నొక్కి మాట్లాడండి",
        transcriptPlaceholder: "మీ మాటలు ఇక్కడ కనిపిస్తాయి...",
        incomeSalesLabel: "ఆదాయం / అమ్మకాలు (₹)",
        expenseCostLabel: "ఖర్చు / కొనుగోలు (₹)",
        entryDescLabel: "వివరణ లేదా వివరాలు",
        saveLedgerEntryBtn: "లెక్కల్లో భద్రపరచండి",
        recentEntriesTitle: "ఇటీవలి లావాదేవీల జాబితా",
        noEntriesYet: "ఇంకా ఎలాంటి లావాదేవీలు లేవు. పైన మైక్ నొక్కి మాట్లాడండి.",
        ledgerEntrySavedToast: "లావాదేవీ భద్రపరచబడింది!",
        artisanCatalogTab: "డిజిటల్ దుకాణం",
        aiSpaceStagerTab: "గది అలంకరణ (AI Decor)",
        reelsToArtisanTab: "రీల్స్ నుండి కళాకారుడి శోధన",
        digitalStorefrontTitle: "మీ ప్రత్యక్ష డిజిటల్ షోరూమ్",
        shareStoreBtn: "దుకాణాన్ని పంచుకోండి",
        shareCraftBtn: "షేర్ చేయండి",
        roomStagerTitle: "గది అలంకరణ (AI స్పేస్ స్టేజర్)",
        roomStagerSubtitle: "ఆధునిక గృహాలలో మీ చేతివృత్తుల కళాఖండాలను అమర్చి చూడండి:",
        selectRoomPreset: "గది రకాన్ని ఎంచుకోండి:",
        roomModernLiving: "ఆధునిక లివింగ్ రూమ్",
        roomCozyBedroom: "సాంప్రదాయ బెడ్ రూమ్",
        roomDiningWall: "డైనింగ్ హాల్ గోడ",
        renderStagedRoomBtn: "గదిలో అమర్చి చూడండి 🎨",
        reelsMatcherTitle: "రీల్స్ నుండి కళాకారుడి శోధన",
        reelsMatcherSubtitle: "సోషల్ మీడియా ఫోటోల ద్వారా అసలైన కళాకారులను కనుగొనండి:",
        reelsDropzoneText: "సోషల్ మీడియా స్క్రీన్‌షాట్ ఇక్కడ వేయండి",
        reelsMatchingBtn: "అసలైన కళాకారుడిని కనుగొనండి 🔍",
        matchFoundTitle: "ధృవీకరించబడిన సంప్రదాయ క్లస్టర్:",
        enableCustomAiLabel: "కస్టమ్ AI మోడల్ API ని ఉపయోగించండి",
        apiEndpointLabel: "API ఎండ్‌పాయింట్ URL",
        apiKeyLabel: "API కీ / టోకెన్",
        profileUpdatedToast: "ప్రొఫైల్ అప్‌డేట్ చేయబడింది!",
        aiConfigSavedToast: "AI సెట్టింగ్‌లు భద్రపరచబడ్డాయి!"
      },

      gu: {
        appName: "કલાસેતુ AI",
        tagline: "કારીગરો માટે ડિજિટલ બિઝનેસ મેનેજર",
        listenTooltip: "અવાજમાં સાંભળો",
        onlineStatus: "ઓનલાઇન · ઇન્ટરનેટ ચાલુ છે",
        offlineStatus: "ઓફલાઇન મોડ · લોકલ સેવ થયું",
        tabCataloger: "બોલીને કેટલોગ",
        tabPricing: "યોગ્ય ભાવ",
        tabHisab: "હિસાબ-કિતાબ",
        tabMarket: "દુકાન અને સજાવટ",
        tabSettings: "પ્રોફાઇલ અને સેટિંગ્સ",
        capturePhoto: "કળાનો ફોટો લો",
        cameraGuide: "કુદરતી રંગો અને આકાર સુરક્ષિત રહેશે",
        holdToSpeak: "બટન દબાવી રાખો અને બોલો",
        releaseToStop: "છોડતાં જ ડિજિટલ લિસ્ટિંગ બની જશે",
        generateDraft: "AI તમારા અવાજથી લિસ્ટિંગ બનાવી રહ્યું છે...",
        listeningText: "સાંભળી રહ્યા છીએ... તમારી ભાષામાં બોલો",
        speechPlaceholder: 'ઉદા. બોલો: "બાંધણી દુપટ્ટો, શુદ્ધ સુતરાઉ, કુદરતી રંગ, ૨ દિવસ લાગ્યા"',
        craftName: "વસ્તુનું નામ",
        craftType: "કળાનો પ્રકાર",
        materials: "વપરાયેલી સામગ્રી",
        dimensions: "માપ / લંબાઈ",
        makingTime: "બનાવવામાં લાગેલા દિવસો",
        careGuide: "સંભાળની સલાહ",
        hindiDesc: "પ્રાદેશિક વિગતો",
        englishDesc: "અંગ્રેજી વિગત (ગ્રાહકો માટે)",
        baseCostLabel: "કુલ ઉત્પાદન ખર્ચ",
        suggestedRange: "AI સૂચવેલ યોગ્ય ભાવ",
        confirmListingBtn: "કેટલોગમાં ઉમેરો",
        shareWhatsappBtn: "વોટ્સએપ પર શેર કરો",
        artisanDecisionNote: "AI માત્ર સલાહ આપશે, અંતિમ નિર્ણય તમારો રહેશે.",
        dailyHisabTitle: "આજનો દૈનિક હિસાબ-કિતાબ",
        hisabPrompt: 'ઉદાહરણ: "આજે ૫૦૦ ના રંગ લીધા અને ૨ દુપટ્ટા ૩૦૦૦ માં વેચ્યા"',
        recordExpenseIncome: "બોલીને ખર્ચ અને કમાણી નોંધો",
        incomeLabel: "આજનું કુલ વેચાણ",
        expenseLabel: "આજનો કુલ ખર્ચ",
        netProfitLabel: "આજનો ચોખ્ખો નફો",
        spaceStagerTitle: "રૂમ સજાવટ (AI ડેકોર)",
        spaceStagerDesc: "દિવાલના ફોટા સાથે તમારી કળા કેવી લાગશે તે જુઓ",
        reelsSearchTitle: "રીલ્સથી કારીગર શોધ",
        reelsSearchDesc: "સોશિયલ મીડિયા સ્ક્રીનશોટથી સીધા સાચા કારીગર શોધો",
        certifiedOrigin: "પ્રમાણિત જીઆઈ ક્લસ્ટર કારીગર",
        listenInstructions: "સૂચનાઓ સાંભળો",
        colorPreservation: "રંગ સુરક્ષા",
        cameraCenterTip: "વસ્તુને ફ્રેમની વચ્ચે રાખો",
        tapToCapture: "ફોટો લેવા ટેપ કરો",
        studioLighting: "લાઇટ સુધારો",
        cleanBackdrop: "બેકગ્રાઉન્ડ સાફ કરો",
        retake: "ફરીથી ફોટો લો",
        step2Title: "વસ્તુ વિશે બોલીને જણાવો",
        voicePromptHelp: "નામ, સામગ્રી અને બનાવવાનો સમય બોલો:",
        sampleVoiceDemo: "⚡ નમૂના અવાજથી ચકાસો",
        step3Title: "AI નિર્મિત કેટલોગ",
        reviewDraft: "ચકાસો",
        authenticityConfirmation: "અધિકૃતતા પુષ્ટિ:",
        genuineHandcrafted: "૧૦૦% અસલી હસ્તકલા વસ્તુ",
        belongsToGiCluster: "નોંધાયેલ જીઆઈ ક્લસ્ટરની વસ્તુ",
        calculatePriceBtn: "વાજબી ભાવ ગણો →",
        approveListingBtn: "કેટલોગમાં મંજૂર કરો ✓",
        listenPricingBreakdown: "ભાવ ગણતરી સાંભળો",
        explainablePricingTitle: "વાજબી ભાવ કેલ્ક્યુલેટર",
        pricingFormulaSubtitle: "દરેક રૂપિયાનો સ્પષ્ટ હિસાબ.",
        rawMaterialCost: "સામગ્રી અને રંગનો ખર્ચ",
        artisanLaborHours: "કારીગરીના કલાકો",
        hourlyWageBenchmark: "કલાકની મજૂરી (₹૮૦/કલાક)",
        giHeritagePremium: "જીઆઈ વારસો રોયલ્ટી (+૧૫%)",
        pricingSummaryTitle: "ભાવ વિગત",
        totalDirectCost: "કુલ ઉત્પાદન ખર્ચ",
        recommendedRetail: "સૂચવેલ છૂટક ભાવ",
        livingWageGuaranteed: "✓ કલાકના ₹૮૦ વેતન + ૧૫% રોયલ્ટી સુનિશ્ચિત.",
        artisanProfileTitle: "કારીગર પ્રોફાઇલ",
        artisanNameLabel: "કારીગરનું નામ",
        craftLineageLabel: "હસ્તકલા વિશેષતા",
        recognizedClusterLabel: "ક્લસ્ટર / પ્રદેશ",
        phoneNumberLabel: "ફોન નંબર",
        updateProfileBtn: "પ્રોફાઇલ અપડેટ કરો",
        selectLanguageTitle: "ભાષા પસંદ કરો",
        chooseLangSubtitle: "તમારી પસંદગીની ભાષા પસંદ કરો:",
        customAiTitle: "AI મોડેલ સેટિંગ્સ",
        customAiSubtitle: "તમારા AI ક્રેડિટ્સ અહીં ઉમેરો:",
        saveAiCredentialsBtn: "સેટિંગ્સ સેવ કરો",
        transparentCostPlus: "પારદર્શક કિંમત નિર્ધારણ મોડેલ",
        formulaCost: "કિંમત",
        formulaMaterial: "કાચો માલ",
        formulaLabor: "મહેનત",
        formulaPackaging: "પેકિંગ",
        formulaTransport: "પરિવહન",
        formulaMargin: "નફો",
        formulaExplanation: "AI માત્ર યોગ્ય કિંમતનું સૂચન કરશે, અંતિમ ભાવ નક્કી કરવો તમારા હાથમાં છે.",
        adjustCostBreakdown: "ખર્ચની વિગતો બદલો:",
        artisanLaborValue: "કારીગરની મહેનત (મજૂરી)",
        ecoPackaging: "ઇકો-ફ્રેન્ડલી પેકિંગ",
        localFreight: "સ્થાનિક પરિવહન ખર્ચ",
        desiredMargin: "અપેક્ષિત નફો (%)",
        totalBaseCost: "કુલ મૂળ ઉત્પાદન ખર્ચ:",
        fairMarketRange: "વાજબી બજાર કિંમત મર્યાદા:",
        yourFinalPrice: "તમારી નક્કી કરેલી અંતિમ કિંમત (₹):",
        lockPriceBtn: "કિંમત સુરક્ષિત કરો",
        priceLockedToast: "કિંમત નક્કી કરવામાં આવી!",
        listenHisabSummary: "હિસાબ અવાજમાં સાંભળો",
        dailyBusinessLedger: "દૈનિક હિસાબ ચોપડો",
        addVoiceLedgerTitle: "બોલીને હિસાબ ઉમેરો",
        holdSpeakEntry: "માઈક દબાવીને હિસાબ બોલો",
        transcriptPlaceholder: "તમારા બોલેલા શબ્દો અહીં દેખાશે...",
        incomeSalesLabel: "આવક / વેચાણ (₹)",
        expenseCostLabel: "ખર્ચ / ખરીદી (₹)",
        entryDescLabel: "વિગત અથવા નોંધ",
        saveLedgerEntryBtn: "ચોપડામાં સાચવો",
        recentEntriesTitle: "તાજેતરના વ્યવહારો",
        noEntriesYet: "હજી કોઈ વ્યવહાર નોંધાયેલ નથી. ઉપર માઈક દબાવીને બોલો.",
        ledgerEntrySavedToast: "વ્યવહાર સાચવી લેવાયો!",
        artisanCatalogTab: "કારીગર ડિજિટલ દુકાન",
        aiSpaceStagerTab: "રૂમ શણગાર (AI Decor)",
        reelsToArtisanTab: "રીલ્સ પરથી કારીગર શોધો",
        digitalStorefrontTitle: "તમારી લાઈવ ડિજિટલ દુકાન",
        shareStoreBtn: "દુકાન શેર કરો",
        shareCraftBtn: "શેર",
        roomStagerTitle: "રૂમ શણગાર (AI સ્પેસ સ્ટેજર)",
        roomStagerSubtitle: "આધુનિક ઘરોમાં તમારી હસ્તકલા ગોઠવીને લાઈવ જુઓ:",
        selectRoomPreset: "રૂમ પ્રકાર પસંદ કરો:",
        roomModernLiving: "આધુનિક લિવિંગ રૂમ",
        roomCozyBedroom: "પરંપરાગત બેડરૂમ",
        roomDiningWall: "ડાઇનિંગ હૉલ દીવાલ",
        renderStagedRoomBtn: "રૂમમાં ગોઠવીને જુઓ 🎨",
        reelsMatcherTitle: "રીલ્સ પરથી કારીગર વિઝ્યુઅલ સર્ચ",
        reelsMatcherSubtitle: "સોશિયલ મીડિયા ફોટો પરથી અસલી કારીગર શોધો:",
        reelsDropzoneText: "સોશિયલ મીડિયા સ્ક્રીનશૉટ અહીં મૂકો",
        reelsMatchingBtn: "અસલી કારીગર શોધો 🔍",
        matchFoundTitle: "પ્રમાણિત પરંપરાગત ક્લસ્ટર ઓળખ:",
        enableCustomAiLabel: "કસ્ટમ AI મોડલ API સક્ષમ કરો",
        apiEndpointLabel: "API એન્ડપોઇન્ટ URL",
        apiKeyLabel: "API કી / ટોકન",
        profileUpdatedToast: "પ્રોફાઇલ અપડેટ થઈ ગઈ!",
        aiConfigSavedToast: "AI સેટિંગ્સ સુરક્ષિત થઈ ગઈ!"
      },

      kn: {
        appName: "ಕಳಾಸೇತು AI",
        tagline: "ಕುಶಲಕರ್ಮಿಗಳ ಡಿಜಿಟಲ್ ವ್ಯಾಪಾರ ಸಹಾಯಕ",
        listenTooltip: "ಧ್ವನಿಯಲ್ಲಿ ಕೇಳಿ",
        onlineStatus: "ಆನ್‌ಲೈನ್ · ಸಿದ್ಧವಾಗಿದೆ",
        offlineStatus: "ಆಫ್‌ಲೈನ್ ಮೋಡ್ · ಸಂಗ್ರಹಿಸಲಾಗಿದೆ",
        tabCataloger: "ಧ್ವನಿ ಕ್ಯಾಟಲಾಗ್",
        tabPricing: "ಸರಿಯಾದ ಬೆಲೆ",
        tabHisab: "ದೈನಂದಿನ ಲೆಕ್ಕ-ಪತ್ರ",
        tabMarket: "ಅಂಗಡಿ ಮತ್ತು ಅಲಂಕಾರ",
        tabSettings: "ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್ಸ್",
        capturePhoto: "ಕರಕುಶಲ ಫೋಟೋ ತೆಗೆಯಿರಿ",
        cameraGuide: "ನೈಸರ್ಗಿಕ ಬಣ್ಣ ಮತ್ತು ನೈಜ ಆಕಾರ ಸುರಕ್ಷಿತವಾಗಿರಲಿದೆ",
        holdToSpeak: "ಒತ್ತಿ ಹಿಡಿದು ವಿವರಗಳನ್ನು ಮಾತನಾಡಿ",
        releaseToStop: "ಬಿಟ್ಟ ತಕ್ಷಣ ಕ್ಯಾಟಲಾಗ್ ಸಿದ್ಧವಾಗುತ್ತದೆ",
        generateDraft: "AI ನಿಮ್ಮ ಧ್ವನಿಯಿಂದ ಕ್ಯಾಟಲಾಗ್ ರಚಿಸುತ್ತಿದೆ...",
        listeningText: "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದ್ದೇವೆ... ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ",
        speechPlaceholder: 'ಉದಾ: "ಚನ್ನಪಟ್ಟಣ ಮರದ ಆಟಿಕೆ, ನೈಸರ್ಗಿಕ ಬಣ್ಣ, 2 ದಿನಗಳು ಬೇಕಾಯಿತು"',
        craftName: "ವಸ್ತುವಿನ ಹೆಸರು",
        craftType: "ಕರಕುಶಲ ವರ್ಗ",
        materials: "ಬಳಸಿದ ಸಾಮಗ್ರಿಗಳು",
        dimensions: "ಅಳತೆ / ಗಾತ್ರ",
        makingTime: "ತಯಾರಿಸಲು ತಗುಲಿದ ಸಮಯ",
        careGuide: "ಕಾಳಜಿ ವಹಿಸುವ ಸೂಚನೆಗಳು",
        hindiDesc: "ಸ್ಥಳೀಯ ವಿವರಣೆ",
        englishDesc: "ಇಂಗ್ಲಿಷ್ ವಿವರಣೆ (ಗ್ರಾಹಕರಿಗೆ)",
        baseCostLabel: "ಒಟ್ಟು ಉತ್ಪಾದನಾ ವೆಚ್ಚ",
        suggestedRange: "AI ಸೂಚಿಸಿದ ನ್ಯಾಯಯುತ ಬೆಲೆ",
        confirmListingBtn: "ಕ್ಯಾಟಲಾಗ್‌ಗೆ ಸೇರಿಸಿ",
        shareWhatsappBtn: "ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ",
        artisanDecisionNote: "AI ಕೇವಲ ಸಲಹೆ ನೀಡುತ್ತದೆ, ಅಂತಿಮ ನಿರ್ಧಾರ ನಿಮ್ಮದೇ.",
        dailyHisabTitle: "ಇಂದಿನ ದೈನಂದಿನ ಲೆಕ್ಕ-ಪತ್ರ (ಹಿಸಾಬ್)",
        hisabPrompt: 'ಉದಾ: "ಇಂದು 500 ಬಣ್ಣಕ್ಕೆ ಖರ್ಚು ಮಾಡಿ 2 ಆಟಿಕೆಗಳನ್ನು 2500 ಕ್ಕೆ ಮಾರಾಟ ಮಾಡಿದೆ"',
        recordExpenseIncome: "ಮಾತನಾಡಿ ಇಂದಿನ ಆದಾಯ ವೆಚ್ಚ ದಾಖಲಿಸಿ",
        incomeLabel: "ಇಂದಿನ ಒಟ್ಟು ಮಾರಾಟ",
        expenseLabel: "ಇಂದಿನ ಒಟ್ಟು ವೆಚ್ಚ",
        netProfitLabel: "ಇಂದಿನ ನಿವ್ವಳ ಲಾಭ",
        spaceStagerTitle: "ಕೋಣೆ ಅಲಂಕಾರ (AI ಡೆಕೋರ್)",
        spaceStagerDesc: "ಗೋಡೆಯ ಫೋಟೋದಲ್ಲಿ ನಿಮ್ಮ ಕಲೆ ಹೇಗೆ ಕಾಣುತ್ತದೆ ಎಂದು ವೀಕ್ಷಿಸಿ",
        reelsSearchTitle: "ರೀಲ್ಸ್‌ನಿಂದ ಕುಶಲಕರ್ಮಿಗಳ ಹುಡುಕಾಟ",
        reelsSearchDesc: "ಸಾಮಾಜಿಕ ಜಾಲತಾಣದ ಸ್ಕ್ರೀನ್‌ಶಾಟ್‌ನಿಂದ ನೈಜ ಕುಶಲಕರ್ಮಿ ಸಂಪರ್ಕಿಸಿ",
        certifiedOrigin: "ದೃಢೀಕೃತ ಜಿಐ ಕ್ಲಸ್ಟರ್ ಕುಶಲಕರ್ಮಿ",
        listenInstructions: "ಸೂಚನೆಗಳನ್ನು ಆಲಿಸಿ",
        colorPreservation: "ಬಣ್ಣದ ರಕ್ಷಣೆ",
        cameraCenterTip: "ವಸ್ತುವನ್ನು ಚೌಕಟ್ಟಿನ ಮಧ್ಯದಲ್ಲಿ ಇರಿಸಿ",
        tapToCapture: "ಫೋಟೋ ತೆಗೆಯಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
        studioLighting: "ಬೆಳಕು ಸುಧಾರಿಸಿ",
        cleanBackdrop: "ಹಿನ್ನೆಲೆ ಸ್ವಚ್ಛಗೊಳಿಸಿ",
        retake: "ಮತ್ತೆ ಫೋಟೋ ತೆಗೆಯಿರಿ",
        step2Title: "ವಸ್ತುವಿನ ವಿವರಗಳನ್ನು ಮಾತನಾಡಿ",
        voicePromptHelp: "ಹೆಸರು, ಸಾಮಗ್ರಿ ಮತ್ತು ಸಮಯವನ್ನು ಹೇಳಿ:",
        sampleVoiceDemo: "⚡ ಮಾದರಿ ಧ್ವನಿಯೊಂದಿಗೆ ಪರೀಕ್ಷಿಸಿ",
        step3Title: "AI ಸಿದ್ಧಪಡಿಸಿದ ಕ್ಯಾಟಲಾಗ್",
        reviewDraft: "ಪರಿಶೀಲಿಸಿ",
        authenticityConfirmation: "ಅಧಿಕೃತತೆ ದೃಢೀಕರಣ:",
        genuineHandcrafted: "100% ಅಪ್ಪಟ ಕರಕುಶಲ ವಸ್ತು",
        belongsToGiCluster: "ನೋಂದಾಯಿತ ಜಿಐ ಕ್ಲಸ್ಟರ್‌ಗೆ ಸೇರಿದೆ",
        calculatePriceBtn: "ನ್ಯಾಯಯುತ ಬೆಲೆ ಲೆಕ್ಕಹಾಕಿ →",
        approveListingBtn: "ಕ್ಯಾಟಲಾಗ್‌ಗೆ ಸೇರಿಸಿ ✓",
        listenPricingBreakdown: "ಬೆಲೆ ವಿವರ ಆಲಿಸಿ",
        explainablePricingTitle: "ನ್ಯಾಯಯುತ ಬೆಲೆ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
        pricingFormulaSubtitle: "ಪ್ರತಿಯೊಂದು ರೂಪಾಯಿಯ ಸ್ಪಷ್ಟ ಲೆಕ್ಕಾಚಾರ.",
        rawMaterialCost: "ಸಾಮಗ್ರಿ ಮತ್ತು ಬಣ್ಣದ ವೆಚ್ಚ",
        artisanLaborHours: "ಕೆಲಸದ ಗಂಟೆಗಳು",
        hourlyWageBenchmark: "ಗಂಟೆಯ ಕೂಲಿ (₹80/ಗಂ)",
        giHeritagePremium: "ಜಿಐ ರಾಯಧನ (+15%)",
        pricingSummaryTitle: "ಬೆಲೆ ವಿವರ",
        totalDirectCost: "ಒಟ್ಟು ಉತ್ಪಾದನಾ ವೆಚ್ಚ",
        recommendedRetail: "ಚಿಲ್ಲರೆ ಬೆಲೆ",
        livingWageGuaranteed: "✓ ಗಂಟೆಗೆ ₹80 ಕೂಲಿ + 15% ರಾಯಧನ ಖಚಿತ.",
        artisanProfileTitle: "ಕುಶಲಕರ್ಮಿ ಪ್ರೊಫೈಲ್",
        artisanNameLabel: "ಕುಶಲಕರ್ಮಿಯ ಹೆಸರು",
        craftLineageLabel: "ಕರಕುಶಲ ಪರಿಣತಿ",
        recognizedClusterLabel: "ಕ್ಲಸ್ಟರ್ / ರಾಜ್ಯ",
        phoneNumberLabel: "ಫೋನ್ ಸಂಖ್ಯೆ",
        updateProfileBtn: "ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಿ",
        selectLanguageTitle: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
        chooseLangSubtitle: "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆರಿಸಿ:",
        customAiTitle: "AI ಮಾದರಿ ಸೆಟ್ಟಿಂಗ್ಸ್",
        customAiSubtitle: "ನಿಮ್ಮ AI ಕ್ರೆಡಿಟ್‌ಗಳನ್ನು ಇಲ್ಲಿ ನಮೂದಿಸಿ:",
        saveAiCredentialsBtn: "ಸೆಟ್ಟಿಂಗ್ಸ್ ಉಳಿಸಿ",
        transparentCostPlus: "ಪಾರದರ್ಶಕ ವೆಚ್ಚದ ಮಾದರಿ",
        formulaCost: "ವೆಚ್ಚ",
        formulaMaterial: "ಕಚ್ಚಾ ಸಾಮಗ್ರಿ",
        formulaLabor: "ಶ್ರಮ",
        formulaPackaging: "ಪ್ಯಾಕಿಂಗ್",
        formulaTransport: "ಸಾರಿಗೆ",
        formulaMargin: "ಲಾಭ",
        formulaExplanation: "AI ಕೇವಲ ನ್ಯಾಯಯುತ ಬೆಲೆಯನ್ನು ಸೂಚಿಸುತ್ತದೆ, ಅಂತಿಮ ಬೆಲೆ ನಿರ್ಧಾರ ನಿಮ್ಮದೇ.",
        adjustCostBreakdown: "ವೆಚ್ಚದ ವಿವರಗಳನ್ನು ಸರಿಹೊಂದಿಸಿ:",
        artisanLaborValue: "ಕುಶಲಕರ್ಮಿಯ ಶ್ರಮದ ಮೌಲ್ಯ",
        ecoPackaging: "ಸುರಕ್ಷಿತ ಪ್ಯಾಕಿಂಗ್",
        localFreight: "ಸ್ಥಳೀಯ ಸಾರಿಗೆ ವೆಚ್ಚ",
        desiredMargin: "ನಿರೀಕ್ಷಿತ ಲಾಭ (%)",
        totalBaseCost: "ಒಟ್ಟು ಮೂಲ ಉತ್ಪಾದನಾ ವೆಚ್ಚ:",
        fairMarketRange: "ನ್ಯಾಯಯುತ ಮಾರುಕಟ್ಟೆ ಬೆಲೆ ಶ್ರೇಣಿ:",
        yourFinalPrice: "ನೀವು ನಿಗದಿಪಡಿಸಿದ ಅಂತಿಮ ಬೆಲೆ (₹):",
        lockPriceBtn: "ಬೆಲೆಯನ್ನು ದೃಢೀಕರಿಸಿ",
        priceLockedToast: "ಬೆಲೆ ದೃಢೀಕರಿಸಲಾಗಿದೆ!",
        listenHisabSummary: "ಲೆಕ್ಕವನ್ನು ಧ್ವನಿಯಲ್ಲಿ ಆಲಿಸಿ",
        dailyBusinessLedger: "ದೈನಂದಿನ ಲೆಕ್ಕದ ಪುಸ್ತಕ",
        addVoiceLedgerTitle: "ಮಾತನಾಡಿ ಲೆಕ್ಕ ದಾಖಲಿಸಿ",
        holdSpeakEntry: "ಮೈಕ್ ಒತ್ತಿ ಹಿಡಿದು ಮಾತನಾಡಿ",
        transcriptPlaceholder: "ನೀವು ಮಾತನಾಡಿದ ಪದಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ...",
        incomeSalesLabel: "ಆದಾಯ / ಮಾರಾಟ (₹)",
        expenseCostLabel: "ವೆಚ್ಚ / ಖರೀದಿ (₹)",
        entryDescLabel: "ವಿವರಣೆ ಅಥವಾ ಟಿಪ್ಪಣಿ",
        saveLedgerEntryBtn: "ಪುಸ್ತಕದಲ್ಲಿ ಉಳಿಸಿ",
        recentEntriesTitle: "ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು",
        noEntriesYet: "ಇನ್ನೂ ಯಾವುದೇ ದಾಖಲೆಗಳಿಲ್ಲ. ಮೇಲೆ ಮೈಕ್ ಒತ್ತಿ ಮಾತನಾಡಿ.",
        ledgerEntrySavedToast: "ವಹಿವಾಟು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!",
        artisanCatalogTab: "ಡಿಜಿಟಲ್ ಅಂಗಡಿ",
        aiSpaceStagerTab: "ಕೋಣೆಯ ಅಲಂಕಾರ (AI Decor)",
        reelsToArtisanTab: "ರೀಲ್ಸ್‌ನಿಂದ ಕುಶಲಕರ್ಮಿ ಹುಡುಕಾಟ",
        digitalStorefrontTitle: "ನಿಮ್ಮ ಲೈವ್ ಡಿಜಿಟಲ್ ಅಂಗಡಿ",
        shareStoreBtn: "ಅಂಗಡಿಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ",
        shareCraftBtn: "ಹಂಚಿ",
        roomStagerTitle: "ಕೋಣೆಯ ಅಲಂಕಾರ (AI ಸ್ಪೇಸ್ ಸ್ಟೇಜರ್)",
        roomStagerSubtitle: "ಆಧುನಿಕ ಮನೆಗಳಲ್ಲಿ ನಿಮ್ಮ ಕಲಾಕೃತಿಗಳನ್ನು ಜೋಡಿಸಿ ನೋಡಿ:",
        selectRoomPreset: "ಕೋಣೆಯ ಮಾದರಿ ಆಯ್ಕೆಮಾಡಿ:",
        roomModernLiving: "ಆಧುನಿಕ ಲಿವಿಂಗ್ ರೂಮ್",
        roomCozyBedroom: "ಸಾಂಪ್ರದಾಯಿಕ ಮಲಗುವ ಕೋಣೆ",
        roomDiningWall: "ಊಟದ ಕೋಣೆ ಗೋಡೆ",
        renderStagedRoomBtn: "ಕೋಣೆಯಲ್ಲಿ ಜೋಡಿಸಿ ನೋಡಿ 🎨",
        reelsMatcherTitle: "ರೀಲ್ಸ್‌ನಿಂದ ಕುಶಲಕರ್ಮಿ ಹುಡುಕಾಟ",
        reelsMatcherSubtitle: "ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಫೋಟೋಗಳಿಂದ ನೈಜ ಕುಶಲಕರ್ಮಿಗಳನ್ನು ಹುಡುಕಿ:",
        reelsDropzoneText: "ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಇಲ್ಲಿ ಹಾಕಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
        reelsMatchingBtn: "ನೈಜ ಕುಶಲಕರ್ಮಿಯನ್ನು ಹುಡುಕಿ 🔍",
        matchFoundTitle: "ದೃಢೀಕರಿಸಿದ ಸಾಂಪ್ರದಾಯಿಕ ಕ್ಲಸ್ಟರ್:",
        enableCustomAiLabel: "ಕಸ್ಟಮ್ AI ಮಾದರಿ API ಬಳಸಿ",
        apiEndpointLabel: "API ಎಂಡ್‌ಪಾಯಿಂಟ್ URL",
        apiKeyLabel: "API ಕೀ / ಟೋಕನ್",
        profileUpdatedToast: "ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲಾಗಿದೆ!",
        aiConfigSavedToast: "AI ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಉಳಿಸಲಾಗಿದೆ!"
      },

      or: {
        appName: "କଳାସେତୁ AI",
        tagline: "କାରିଗରମାନଙ୍କ ଡିଜିଟାଲ ବ୍ୟବସାୟ ସାଥୀ",
        listenTooltip: "ଭଏସରେ ଶୁଣନ୍ତୁ",
        onlineStatus: "ଅନଲାଇନ୍ · ପ୍ରସ୍ତୁତ",
        offlineStatus: "ଅଫଲାଇନ୍ ମୋଡ୍ · ସୁରକ୍ଷିତ",
        tabCataloger: "ଭଏସ୍ କ୍ୟାଟାଲଗ୍",
        tabPricing: "ଉଚିତ ମୂଲ୍ୟ",
        tabHisab: "ହିସାବ-କିତାବ",
        tabMarket: "ଦୋକାନ ଓ ସଜାବଟ",
        tabSettings: "ପ୍ରୋଫାଇଲ୍ ଓ ସେଟିଂସ୍",
        capturePhoto: "ଶିଳ୍ପର ଫଟୋ ଉଠାନ୍ତୁ",
        cameraGuide: "ପ୍ରାକୃତିକ ରଙ୍ଗ ଓ ଆକାର ସୁରକ୍ଷିତ ରହିବ",
        holdToSpeak: "ଚାପି ଧରି ସାମଗ୍ରୀ ବିଷୟରେ କୁହନ୍ତୁ",
        releaseToStop: "ଛାଡ଼ିଦେଲେ ଡିଜିଟାଲ୍ ତାଲିକା ପ୍ରସ୍ତୁତ ହୋଇଯିବ",
        generateDraft: "AI ଆପଣଙ୍କ ଭଏସରୁ ତାଲିକା ତିଆରି କରୁଛି...",
        listeningText: "ଶୁଣୁଛୁ... ଆପଣଙ୍କ ଭାଷାରେ କୁହନ୍ତୁ",
        speechPlaceholder: 'ଯେପରି କୁହନ୍ତୁ: "କଟକ ତାରାକସି ରୂପା କାମ, ୩ ଦିନ ସମୟ ଲାଗିଲା"',
        craftName: "ସାମଗ୍ରୀ ନାମ",
        craftType: "ଶିଳ୍ପ ବିଭାଗ",
        materials: "ବ୍ୟବହୃତ ସାମଗ୍ରୀ",
        dimensions: "ଆକାର / ମାପ",
        makingTime: "ତିଆରି ସମୟ",
        careGuide: "ଯତ୍ନ ପରାମର୍ଶ",
        hindiDesc: "ଆଞ୍ଚଳିକ ବିବରଣୀ",
        englishDesc: "ଇଂରାଜୀ ବିବରଣୀ (ଗ୍ରାହକଙ୍କ ପାଇଁ)",
        baseCostLabel: "ମୋଟ ନିର୍ମାଣ ଖର୍ଚ୍ଚ",
        suggestedRange: "AI ପ୍ରସ୍ତାବିତ ଉଚିତ ମୂଲ୍ୟ",
        confirmListingBtn: "କ୍ୟାଟାଲଗ୍‌ରେ ଯୋଡନ୍ତୁ",
        shareWhatsappBtn: "ହ୍ୱାଟ୍ସଆପ୍‌ରେ ସେୟାର କରନ୍ତୁ",
        artisanDecisionNote: "AI କେବଳ ପରାମର୍ଶ ଦେବ, ଚୂଡ଼ାନ୍ତ ନିଷ୍ପତ୍ତି ଆପଣଙ୍କର।",
        dailyHisabTitle: "ଆଜିର ଦୈନିକ ହିସାବ-କିତାବ",
        hisabPrompt: 'ଯେପରି କୁହନ୍ତୁ: "ଆଜି ୫୦୦ ଟଙ୍କାର ରଙ୍ଗ କିଣିଲି ଓ ୨ଟି ଜିନିଷ ୩୦୦୦ରେ ବିକିଲି"',
        recordExpenseIncome: "କହିକରି ଆଜିର ଖର୍ଚ୍ଚ ଓ ଆୟ ଦାଖଲ କରନ୍ତୁ",
        incomeLabel: "ଆଜିର ମୋଟ ବିକ୍ରି",
        expenseLabel: "ଆଜିର ମୋଟ ଖର୍ଚ୍ଚ",
        netProfitLabel: "ଆଜିର ଲାଭ",
        spaceStagerTitle: "ଘର ସଜାବଟ (AI ଡେକୋର୍)",
        spaceStagerDesc: "କାନ୍ଥ ଫଟୋରେ ଆପଣଙ୍କ କଳା କିପରି ଶୋଭା ପାଇବ ଦେଖନ୍ତୁ",
        reelsSearchTitle: "ରିଲ୍ସରୁ କାରିଗର ସନ୍ଧାନ",
        reelsSearchDesc: "ସୋସିଆଲ ମିଡିଆ ଫଟୋରୁ ପ୍ରକୃତ କାରିଗରଙ୍କୁ ଖୋଜନ୍ତୁ",
        certifiedOrigin: "ପ୍ରମାଣିତ ଜିଆଇ କ୍ଲଷ୍ଟର କାରିଗର",
        listenInstructions: "ନିର୍ଦ୍ଦେଶ ଶୁଣନ୍ତୁ",
        colorPreservation: "ରଙ୍ଗ ସୁରକ୍ଷା",
        cameraCenterTip: "ସାମଗ୍ରୀକୁ ମଝିରେ ରଖନ୍ତୁ",
        tapToCapture: "ଫଟୋ ଉଠାଇବା ପାଇଁ ଟ୍ୟାପ୍ କରନ୍ତୁ",
        studioLighting: "ଆଲୋକ ସୁଧାରନ୍ତୁ",
        cleanBackdrop: "ପଛପଟ ସଫା କରନ୍ତୁ",
        retake: "ପୁଣି ଫଟୋ ନିଅନ୍ତୁ",
        step2Title: "ସାମଗ୍ରୀ ବିଷୟରେ କୁହନ୍ତୁ",
        voicePromptHelp: "ନାମ, କପଡ଼ା ଏବଂ ସମୟ କୁହନ୍ତୁ:",
        sampleVoiceDemo: "⚡ ନମୁନା ଭଏସରେ ଚେକ୍ କରନ୍ତୁ",
        step3Title: "AI ନିର୍ମିତ କ୍ୟାଟାଲଗ୍",
        reviewDraft: "ଯାଞ୍ଚ କରନ୍ତୁ",
        authenticityConfirmation: "ସତ୍ୟତା ପ୍ରମାଣୀକରଣ:",
        genuineHandcrafted: "୧୦୦% ଅସଲି ହସ୍ତନିର୍ମିତ ସାମଗ୍ରୀ",
        belongsToGiCluster: "ପଞ୍ଜୀକୃତ ଜିଆଇ କ୍ଲଷ୍ଟର ଅନ୍ତର୍ଭୁକ୍ତ",
        calculatePriceBtn: "ଉଚିତ ମୂଲ୍ୟ ହିସାବ କରନ୍ତୁ →",
        approveListingBtn: "କ୍ୟାଟାଲଗ୍‌ରେ ଯୋଡନ୍ତୁ ✓",
        listenPricingBreakdown: "ମୂଲ୍ୟ ଗଣନା ଶୁଣନ୍ତୁ",
        explainablePricingTitle: "ଉଚିତ ମୂଲ୍ୟ କାଲକୁଲେଟର",
        pricingFormulaSubtitle: "ପ୍ରତ୍ୟେକ ଟଙ୍କାର ସ୍ପଷ୍ଟ ହିସାବ।",
        rawMaterialCost: "କଞ୍ଚାମାଲ ଓ ରଙ୍ଗ ଖର୍ଚ୍ଚ",
        artisanLaborHours: "କାରିଗରୀ ସମୟ (ଘଣ୍ଟା)",
        hourlyWageBenchmark: "ଘଣ୍ଟା ପିଛା ମଜୁରୀ (₹୮୦/ଘଣ୍ଟା)",
        giHeritagePremium: "ଜିଆଇ ଐତିହ୍ୟ ରୟାଲଟି (+୧୫%)",
        pricingSummaryTitle: "ମୂଲ୍ୟ ବିବରଣୀ",
        totalDirectCost: "ମୋଟ ନିର୍ମାଣ ଖର୍ଚ୍ଚ",
        recommendedRetail: "ପ୍ରସ୍ତାବିତ ଖୁଚୁରା ମୂଲ୍ୟ",
        livingWageGuaranteed: "✓ ଘଣ୍ଟାକୁ ₹୮୦ ମଜୁରୀ + ୧୫% ରୟାଲଟି ସୁନିଶ୍ଚିତ।",
        artisanProfileTitle: "କାରିଗର ପ୍ରୋଫାଇଲ୍",
        artisanNameLabel: "କାରିଗରଙ୍କ ନାମ",
        craftLineageLabel: "ହସ୍ତଶିଳ୍ପ ବିଶେଷତ୍ୱ",
        recognizedClusterLabel: "କ୍ଲଷ୍ଟର / ଅଞ୍ଚଳ",
        phoneNumberLabel: "ଫୋନ୍ ନମ୍ବର",
        updateProfileBtn: "ପ୍ରୋଫାଇଲ୍ ଅପଡେଟ୍ କରନ୍ତୁ",
        selectLanguageTitle: "ଭାଷା ଚୟନ କରନ୍ତୁ",
        chooseLangSubtitle: "ଆପଣଙ୍କ ପସନ୍ଦର ଭାଷା ବାଛନ୍ତୁ:",
        customAiTitle: "AI ମଡେଲ୍ ସେଟିଂସ୍",
        customAiSubtitle: "ଆପଣଙ୍କ AI କ୍ରେଡିଟ୍ ଏଠାରେ ଯୋଡନ୍ତୁ:",
        saveAiCredentialsBtn: "ସେଟିଂସ୍ ସେଭ୍ କରନ୍ତୁ",
        transparentCostPlus: "ସ୍ୱଚ୍ଛ ଉତ୍ପାଦନ ମୂଲ୍ୟ ମଡେଲ୍",
        formulaCost: "ମୂଲ୍ୟ",
        formulaMaterial: "କଞ୍ଚାମାଲ",
        formulaLabor: "ଶ୍ରମ",
        formulaPackaging: "ପ୍ୟାକିଂ",
        formulaTransport: "ପରିବହନ",
        formulaMargin: "ଲାଭ",
        formulaExplanation: "AI କେବଳ ଉଚିତ ମୂଲ୍ୟ ପରାମର୍ଶ ଦେବ, ଚୂଡ଼ାନ୍ତ ଦାମ୍ ନିଷ୍ପତ୍ତି ଆପଣଙ୍କର।",
        adjustCostBreakdown: "ଖର୍ଚ୍ଚ ବିବରଣୀ ସଜାଡ଼ନ୍ତୁ:",
        artisanLaborValue: "କାରିଗରୀ ଶ୍ରମ ମୂଲ୍ୟ",
        ecoPackaging: "ପରିବେଶ ଅନୁକୂଳ ପ୍ୟାକିଂ",
        localFreight: "ସ୍ଥାନୀୟ ପରିବହନ ଖର୍ଚ୍ଚ",
        desiredMargin: "ଆଶା କରାଯାଉଥିବା ଲାଭ (%)",
        totalBaseCost: "ମୋଟ ମୌଳିକ ନିର୍ମାଣ ଖର୍ଚ୍ଚ:",
        fairMarketRange: "ଉଚିତ ବଜାର ଦର ପରିସର:",
        yourFinalPrice: "ଆପଣଙ୍କ ଚୂଡ଼ାନ୍ତ ବିକ୍ରୟ ଦାମ୍ (₹):",
        lockPriceBtn: "ଦାମ୍ ନିଶ୍ଚିତ କରନ୍ତୁ",
        priceLockedToast: "ଦାମ୍ ସଫଳତାର ସହ ସେଭ୍ ହେଲା!",
        listenHisabSummary: "ହିସାବ ସ୍ୱରରେ ଶୁଣନ୍ତୁ",
        dailyBusinessLedger: "ଦୈନିକ ଖାତା",
        addVoiceLedgerTitle: "କହିକରି ହିସାବ ଯୋଡ଼ନ୍ତୁ",
        holdSpeakEntry: "ମାଇକ୍ ଚାପି ହିସାବ କୁହନ୍ତୁ",
        transcriptPlaceholder: "ଆପଣ କହିଥିବା କଥା ଏଠାରେ ଦେଖାଯିବ...",
        incomeSalesLabel: "ଆୟ / ବିକ୍ରି (₹)",
        expenseCostLabel: "ବ୍ୟୟ / କ୍ରୟ (₹)",
        entryDescLabel: "ବିବରଣୀ ବା ଟିପ୍ପଣୀ",
        saveLedgerEntryBtn: "ଖାତାରେ ସେଭ୍ କରନ୍ତୁ",
        recentEntriesTitle: "ସାମ୍ପ୍ରତିକ ଲେନଦେନ୍ ତାଲିକା",
        noEntriesYet: "କୌଣସି ହିସାବ ଯୋଡ଼ାଯାଇନାହିଁ। ଉପରେ ମାଇକ୍ ଚାପି କୁହନ୍ତୁ।",
        ledgerEntrySavedToast: "ହିସାବ ସଫଳତାର ସହ ସେଭ୍ ହେଲା!",
        artisanCatalogTab: "କାରିଗର ଡିଜିଟାଲ୍ ଦୋକାନ",
        aiSpaceStagerTab: "ଘର ସଜାଣି (AI Decor)",
        reelsToArtisanTab: "ରିଲ୍ସରୁ କାରିଗର ସନ୍ଧାନ",
        digitalStorefrontTitle: "ଆପଣଙ୍କ ଲାଇଭ୍ ଡିଜିଟାଲ୍ ଦୋକାନ",
        shareStoreBtn: "ଦୋକାନ ଶେୟାର କରନ୍ତୁ",
        shareCraftBtn: "ଶେୟାର",
        roomStagerTitle: "ଘର ସଜାଣି (AI ରୁମ୍ ଷ୍ଟେଜର୍)",
        roomStagerSubtitle: "ଆଧୁନିକ ଘରେ ନିଜ ହସ୍ତଶିଳ୍ପ ସଜାଇ ଦେଖନ୍ତୁ:",
        selectRoomPreset: "ଘର ପ୍ରକାର ବାଛନ୍ତୁ:",
        roomModernLiving: "ଆଧୁନିକ ଲିଭିଙ୍ଗ୍ ରୁମ୍",
        roomCozyBedroom: "ପାରମ୍ପରିକ ଶୋଇବା ଘର",
        roomDiningWall: "ଡାଇନିଂ ହଲ୍ କାନ୍ଥ",
        renderStagedRoomBtn: "ଘରେ ସଜାଇ ଦେଖନ୍ତୁ 🎨",
        reelsMatcherTitle: "ରିଲ୍ସରୁ କାରିଗର ଭିଜୁଆଲ୍ ସନ୍ଧାନ",
        reelsMatcherSubtitle: "ସୋସିଆଲ୍ ମିଡିଆ ଫଟୋରୁ ପ୍ରକୃତ କାରିଗରଙ୍କୁ ଖୋଜନ୍ତୁ:",
        reelsDropzoneText: "ଫଟୋ ଏଠାରେ ଟାଣି ଆଣନ୍ତୁ ବା ଅପଲୋଡ୍ କରନ୍ତୁ",
        reelsMatchingBtn: "ପ୍ରକୃତ କାରିଗର ଖୋଜନ୍ତୁ 🔍",
        matchFoundTitle: "ପ୍ରମାଣିତ ପାରମ୍ପରିକ କ୍ଲଷ୍ଟର:",
        enableCustomAiLabel: "କଷ୍ଟମ୍ AI ମଡେଲ୍ API ବ୍ୟବହାର କରନ୍ତୁ",
        apiEndpointLabel: "API ଏଣ୍ଡପଏଣ୍ଟ URL",
        apiKeyLabel: "API କୀ / ଟୋକନ୍",
        profileUpdatedToast: "ପ୍ରୋଫାଇଲ୍ ଅପଡେଟ୍ ହେଲା!",
        aiConfigSavedToast: "AI ସେଟିଂସ୍ ସେଭ୍ ହେଲା!"
      }
    };

    // Setup network listeners
    if (typeof window !== 'undefined') {
      window.addEventListener('online', () => {
        this.set('online', true);
        this.emit('networkChanged', true);
      });
      window.addEventListener('offline', () => {
        this.set('online', false);
        this.emit('networkChanged', false);
      });
    }
  }

  get(key) {
    return this.state[key];
  }

  set(key, value) {
    this.state[key] = value;
    if (key === 'language') {
      localStorage.setItem('kalasetu_lang', value);
    } else if (key === 'artisan') {
      localStorage.setItem('kalasetu_artisan', JSON.stringify(value));
    } else if (key === 'userRole') {
      localStorage.setItem('kalasetu_role', value);
    } else if (key === 'speechConfig') {
      localStorage.setItem('kalasetu_speech_config', JSON.stringify(value));
    }
    this.emit(key, value);
    this.emit('stateChange', { key, value });
  }

  t(key, fallback = null) {
    const lang = this.state.language;
    if (this.translations[lang] && this.translations[lang][key]) {
      return this.translations[lang][key];
    }
    if (this.translations.hi && this.translations.hi[key]) {
      return this.translations.hi[key];
    }
    return this.translations.en[key] || fallback || key;
  }

  on(event, callback) {
    if (!this.listeners[event]) {
      this.listeners[event] = [];
    }
    this.listeners[event].push(callback);
    return () => {
      this.listeners[event] = this.listeners[event].filter(cb => cb !== callback);
    };
  }

  emit(event, data) {
    if (this.listeners[event]) {
      this.listeners[event].forEach(cb => cb(data));
    }
  }

  showToast(message, type = 'info') {
    const container = document.getElementById('toast-container');
    if (!container) return;

    const toast = document.createElement('div');
    toast.className = `toast toast-${type} animate-slide-up`;
    toast.innerHTML = `
      <span>${type === 'success' ? '✓' : type === 'warning' ? '⚠️' : 'ℹ️'}</span>
      <span>${message}</span>
    `;

    container.appendChild(toast);

    setTimeout(() => {
      toast.classList.add('toast-fade');
      setTimeout(() => toast.remove(), 300);
    }, 2800);
  }
}

export const appState = new AppState();
